### ISSUE TITLE
github installation fails

### ISSUE THREAD

**Issue by homerhanumat** [eddelbuettel/drat#1]
Looks like an interesting package.  I cannot install it from Git Hub, though:

```
> devtools::install_github("eddelbuettel/drat")
Downloading github repo eddelbuettel/drat@master
Error: Found continuation line starting ' Two primary types o ...' at begin of record.
```

**Comment by eddelbuettel** [comment]
I don;t use devtools, so maybe talk to @hadley? 

I give instructions to get started from CRAN, and that works for me.

**Comment by homerhanumat** [comment]
Yes, from CRAN:

```
install.packages("drat",type="source")
```
worked fine.  Maybe the Windows binaries have not yet been made.  (I usually use Linux anyway.)

Thanks,
Homer

**Comment by eddelbuettel** [comment]
Seemingly, devtools does not like how the `DESCRIPTION` file is formatted with the continuation line.  As the file is legal for R itself, I would have to think that this is indeed a devtools corner case.

**Comment by eddelbuettel** [comment]
Fixed at my end (see below); still a bug (presumably known) in devtools -- ccing @hadley 

```{r}
R> devtools::install_github("eddelbuettel/drat")
Downloading github repo eddelbuettel/drat@master
Installing drat
'/usr/lib/R/bin/R' --vanilla CMD INSTALL '/tmp/RtmpztQgSR/devtools22fc5f4ef611/eddelbuettel-drat-830e07d' --library='/usr/local/lib/R/site-library'  \
  --install-tests 

* installing *source* package ‘drat’ ...
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (drat)
R> 
```
