### ISSUE TITLE
New error on Ubuntu

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/drat#103]
No luck @FelixErnst :-/   I submitted the release candidate to rhub's `check_for_cran()` and it pukes:

```
drat 0.1.7: ERROR

Build ID:   drat_0.1.7.tar.gz-3a4a1fbbd13641d58b89246467b5c4aa
Platform:   Ubuntu Linux 16.04 LTS, R-release, GCC
Submitted:  6 minutes 2.3 seconds ago
Build time: 6 minutes 0.3 seconds

ERRORS:
-------
* checking tests ...
  Running ‘simpleTests.R’
  Running ‘skeleton_git2r.R’
 ERROR
Running the tests in ‘tests/skeleton_git2r.R’ failed.
Last 13 lines of output:
  * saving partial Rd database
  * checking for LF line-endings in source and make files and shell scripts
  * checking for empty or unneeded directories
  * building ‘foo_1.0.tar.gz’
  
  dratting
  Added and committed foo_1.0.tar.gz plus PACKAGES files. Still need to push.

  > testRepoActions(repodir)                                                                                                                                                                                       
  Error in testRepoActions(repodir) :
    Wrong package files found after pruning for version = NA
  In addition: Warning message:
  In (function (dir = ".", fields = NULL, type = c("source", "mac.binary",  :
    PACKAGES files do not include MD5 sums in the win.binary case, so strict checking is impossible. Calling down to write_PACKAGES directly.
  Execution halted



See the full build log:
HTML: https://builder.r-hub.io/status/drat_0.1.7.tar.gz-3a4a1fbbd13641d58b89246467b5c4aa
Text: https://builder.r-hub.io/status/original/drat_0.1.7.tar.gz-3a4a1fbbd13641d58b89246467b5c4aa
Artifacts: https://artifacts.r-hub.io/drat_0.1.7.tar.gz-3a4a1fbbd13641d58b89246467b5c4aa

Have questions, suggestions or want to report a bug?
Please file an issue ticket at GitHub at
https://github.com/r-hub/rhub/issues
```

Can you please investigate, and maybe make use of as wide a test grid as you can?

**Comment by eddelbuettel** [comment]
(On better news, it passes with win-builder's r-release and r-devel, and the other two machines at RHub invoked by `check_for_cran()`, namely fedora-clang-rdevel and windows-rdevel.)

**Comment by eddelbuettel** [comment]
I also updated my `r-devel` and it does not croak.  Maybe just take another good look at -- I certainly have had false positives from RHub for other packages.

**Comment by FelixErnst** [comment]
Hi @eddelbuettel ,

I cannot replicate the error in r78795 using the `rocker/rstudio:devel` image.

Maybe be something else is going on.

Felix

<details><summary>Build output</summary>
<pre>
==> devtools::check(document = FALSE)

── Building ────────────────────────────────────────────────────────────────────────────────────── drat ──
Setting env vars:
● CFLAGS    : -Wall -pedantic -fdiagnostics-color=always
● CXXFLAGS  : -Wall -pedantic -fdiagnostics-color=always
● CXX11FLAGS: -Wall -pedantic -fdiagnostics-color=always
──────────────────────────────────────────────────────────────────────────────────────────────────────────
✓  checking for file ‘/home/rstudio/drat/DESCRIPTION’ ...
─  preparing ‘drat’:
✓  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes
✓  creating vignettes (2.5s)
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘drat_0.1.6.3.tar.gz’
   
── Checking ────────────────────────────────────────────────────────────────────────────────────── drat ──
Setting env vars:
● _R_CHECK_CRAN_INCOMING_REMOTE_: FALSE
● _R_CHECK_CRAN_INCOMING_       : FALSE
● _R_CHECK_FORCE_SUGGESTS_      : FALSE
● NOT_CRAN                      : true
── R CMD check ─────────────────────────────────────────────────────────────────
─  using log directory ‘/home/rstudio/drat.Rcheck’
─  using R Under development (unstable) (2020-07-09 r78795)
─  using platform: x86_64-pc-linux-gnu (64-bit)
─  using session charset: UTF-8
─  using options ‘--no-manual --as-cran’
✓  checking for file ‘drat/DESCRIPTION’
─  checking extension type ... Package
─  this is package ‘drat’ version ‘0.1.6.3’
─  package encoding: UTF-8
✓  checking package namespace information
✓  checking package dependencies (3s)
✓  checking if this is a source package
✓  checking if there is a namespace
✓  checking for executable files ...
✓  checking for hidden files and directories
✓  checking for portable file names ...
✓  checking for sufficient/correct file permissions
✓  checking serialization versions
✓  checking whether package ‘drat’ can be installed (1.3s)
✓  checking installed package size
✓  checking package directory
✓  checking for future file timestamps (612ms)
✓  checking ‘build’ directory
✓  checking DESCRIPTION meta-information ...
✓  checking top-level files ...
✓  checking for left-over files
✓  checking index information ...
✓  checking package subdirectories (335ms)
✓  checking R files for non-ASCII characters ...
✓  checking R files for syntax errors ... 
✓  checking whether the package can be loaded ...
✓  checking whether the package can be loaded with stated dependencies ...
✓  checking whether the package can be unloaded cleanly ...
✓  checking whether the namespace can be loaded with stated dependencies ...
✓  checking whether the namespace can be unloaded cleanly ...
✓  checking loading without being on the library search path ...
✓  checking dependencies in R code ...
✓  checking S3 generic/method consistency (478ms)
✓  checking replacement functions ...
✓  checking foreign function calls ...
✓  checking R code for possible problems (2s)
✓  checking Rd files ...
✓  checking Rd metadata ...
✓  checking Rd line widths ...
✓  checking Rd cross-references ...
✓  checking for missing documentation entries ...
✓  checking for code/documentation mismatches ...
✓  checking Rd \usage sections (601ms)
✓  checking Rd contents ...
✓  checking for unstated dependencies in examples ...
    WARNING
   ‘qpdf’ is needed for checks on size reduction of PDFs
✓  checking installed files from ‘inst/doc’ ...
✓  checking files in ‘vignettes’
✓  checking examples (602ms)
✓  checking for unstated dependencies in ‘tests’ ...
─  checking tests ...
✓  Running ‘simpleTests.R’
✓  Running ‘skeleton_git2r.R’ (2.8s)
✓  checking for unstated dependencies in vignettes (3s)
✓  checking package vignettes in ‘inst/doc’ ...
✓  checking re-building of vignette outputs (2.7s)
✓  checking for non-standard things in the check directory
✓  checking for detritus in the temp directory
   
   See
     ‘/home/rstudio/drat.Rcheck/00check.log’
   for details.
   
   
── R CMD check results ─────────────────────────────────────── drat 0.1.6.3 ────
Duration: 18.1s

> checking for unstated dependencies in examples ... OK
   WARNING
  ‘qpdf’ is needed for checks on size reduction of PDFs

0 errors ✓ | 1 warning x | 0 notes ✓
Error: R CMD check found WARNINGs
Execution halted

Exited with status 1.
</pre>
</details>

**Comment by eddelbuettel** [comment]
I also could not get it to misbehave here, so I think I ~will~ just ship it as is.  Done.

**Comment by eddelbuettel** [comment]
And on CRAN -- thanks for all your help!
