### ISSUE TITLE
Less ambitious testing?

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/drat#104]
@FelixErnst please take a look at https://cloud.r-project.org/web/checks/check_results_drat.html

Should we ... simply skip test on oldrel?

**Comment by FelixErnst** [comment]
I am sorry for that. This didn't turned out as I expected... or lets say easy/straight forward.

I installed r-oldrel and tested it now on release and oldrel. I fixed the one error by introduced a conditon during testing.

See #105

**Comment by eddelbuettel** [comment]
You're very committed to this.  I would have skipped it :)

**Comment by FelixErnst** [comment]
In for a penny, in for a pound? Thats a saying isn't it?

**Comment by eddelbuettel** [comment]
Fixed by #105 -- thanks!

**Comment by FelixErnst** [comment]
Closed?

**Comment by eddelbuettel** [comment]
Apparently I meant to but forgot...  Trying again :)
