### ISSUE TITLE
drat - Additional_repositories not pass R CMD check if 

### ISSUE THREAD

**Issue by tankwin08** [eddelbuettel/drat#106]
Hi Dirk,

Hope you are doing well.
Thanks very much for your wonderful work on drat.
I used your package to host an external reposity, non-CRAN (rPeaks) last year to make my package waveformlidar (https://github.com/tankwin08/waveformlidar) work well in CRAN.

This year, I plan to submit a new version to CRAN, but it gives me an error: 
Package suggested but not available for checking: 'rPeaks'

I followed the instruction as you suggested in the website (https://cran.r-project.org/web/packages/drat/vignettes/DratForPackageAuthors.html)

I can see the rPeaks in the drat  (https://github.com/tankwin08/drat/tree/gh-pages/src/contrib).
My DESCRIPTION has: Additional_repositories: https://tankwin08.github.io/drat

If I install rPeaks first it can pass CMD check. I wonder how should I deal with this part when I submit to CRAN? As they will not load this package automatically.

Best
Tan

**Comment by eddelbuettel** [comment]
1. It is `drat`, not dart. 

2. See _Writing R Extensions_ for the details, or our R Journal paper for a kinder walkthrough.  

3. _Additional Repositories:_ is of _optonal_ packages.  Optional means not automatically installed.  Maybe you simple need to test if the _optional_ package is in fact present (as it may be on _your_ computer but not CRAN's.

**Comment by tankwin08** [comment]
Thanks, Dirk.
After setting up the drat. I installed rPeaks:

drat::addRepo("tankwin08")
install.packages("rPeaks")

This can pass the R CMD check in my local computer. But it gives the same error (Package suggested but not available for checking: 'rPeaks') and comes back to original point.

I wonder any suggestions on this part?

**Comment by eddelbuettel** [comment]
We're going in circles.  

I already told in email (while urging you to post here) that *your repository contains `rPeaks`*.  Your repo is ok.  Got it?

I also told you twice already that there is a difference between *required packages* (`Depends:`, `Imports:`) and *optional packages* (`Suggests:`, your `Additional_repositories`).  

You. Cannot. Assume. A. Package. From. An. Additional. Repository. Is. Present.  Got that  

You need to *test for it being present* to make its use *conditional on it being installed*.

I do not know how else to tell you that.

**Comment by tankwin08** [comment]
Yes. It can install rPeaks from dart repo.
I will check other parts. Again, many thanks.
