### ISSUE TITLE
Using git depth on gh-pages

### ISSUE THREAD

**Issue by csgillespie** [eddelbuettel/drat#109]
As you know, I use drat + Travis. Over time `gh-pages` has significantly increased in size. I've found that setting the `depth` to 1 on Travis knocked a minute off my build time! 

I'm happy to add a note to the drat/travis vignette, but didn't know if there was somewhere else to mention this?

**Comment by eddelbuettel** [comment]
That is actual and somewhat profound problem that I am struggling with.  I want 'drat' at GitHub to be the source of reference for _using_ the package in the sense of reading about the package and seeing its code.   And we have also used it for a quick-and-dirty tip of  "to get started just fork the drat repo" for _forking_ the repo as a base.  And with added docs, this bites as you noticed.

They are in conflict.  Now, I am surprised to see you as a very experienced and long-time drat use still 'fork'.  Why?   Do we need a new better/slight 'create drat repo from scratch' helper?

Then again your note is hopeful. We can document  `git depth` or `single-branch` or ... but fundamentally I think it is the wrong approach _as I think users will not type the extra option_ and we do not offer is programmatically (unless I am forgetting something). 

Maybe we need a different "and always lightweight / empty" repo to clone from?

Really glad you brought this up. It needs resolution one way or another but I am unsure how.

**Comment by eddelbuettel** [comment]
Or if you meant 'just in your local use of drat` then how you invoke `git clone` is of course up to you.  Add it there, and we document in the FAQ?

**Comment by csgillespie** [comment]
>  'just in your local use of drat

Yes ;)

> Now, I am surprised to see you as a very experienced and long-time drat use still 'fork'.

I forked it once right at the beginning. It _just_ works and googling suggests I can't easily remove the "fork" flag.

If I was to start a new one, then I would create a clean repo.

> Maybe we need a different "and always lightweight / empty" repo to clone from?

Yep. I suppose they just need to create an empty repo and add `gh-pages`. Then a simple initialise function would do it?

**Comment by eddelbuettel** [comment]
As for 'slim checkout from a large repo' I also do 

```
git clone --single-branch --branch name-of-branch-here https://github.com/somOrg/someRepo newdir
```

in some places.  Maybe try that?  (I had not used --single-branch before. It rocks for dev or rel branches if you just want that.)

**Comment by eddelbuettel** [comment]
This can be closed, the lack of following suggests the issue is addressed.  If more is needed please reopen and ideally demonstrate with small reproducible examples why.
