### ISSUE TITLE
Problem with link checker in r-devel

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/drat#120]
We have a problem with r-devel and the link checker:

```
  URL: https://github.com/YourName/drat
    From: inst/doc/DratStepByStep.html
    Status: 404                                                                                          
    Message: Not Found                           
  URL: https://github.com/donaldduck/quacking
    From: inst/doc/DratStepByStep.html
    Status: 404                                                                                          
    Message: Not Found
  URL: https://yourname.github.io/drat
    From: inst/doc/DratStepByStep.html
    Status: 404
    Message: Not Found  
```
    
The 'yourname/drat' repo does not exist, so I suggest we use, say, 'drat-base/drat' or 'ghrr/drat'.    

The 'donaldduck/quacking' repo does not exist, and as we need something that exists but is not on CRAN and preferably small I suggest we use 'eddelbuettel/curses'.

/cc @RomanHornung

**Comment by eddelbuettel** [comment]
One solution would be to just turn to formatted text _i.e._ `https://github.com/donaldduck/quacking` which is done in other places in the documentation.

**Comment by eddelbuettel** [comment]
That was the simplest fix so done.  Now (along with earlier commits) back to `R-devel CMD check --as-cran` clean.

**Comment by RomanHornung** [comment]
Thanks for the notification. For me it would be fine to use 'eddelbuettel/curses'.
