### ISSUE TITLE
drat 0.2.0: breaking change if `dratBranch = "main"`

### ISSUE THREAD

**Issue by pat-s** [eddelbuettel/drat#122]
The new release errors if one uses `dratBranch = "main"` (or anything other than "gh-pages" or "docs"):

```r
  9.   └─drat::insertPackage(...)
 10.     └─drat:::.check_location_arg(location)

Error: The 'location' argument 'main' is unsuitable.
```

I've adjusted to "docs" as the equivalent of the default branch now but wanted to let people know.

Luckily the new way seems to be backward compatible.

**Comment by eddelbuettel** [comment]
> I've adjusted to "docs" 

I cannot parse that. Exactly _what_ did you do?   Maybe you can add the config snippet you used in your aim is to help others (which I commend).

We had the 0.1.8.* pre-release out for always two weeks for people to do exactly these checks prior to the 0.2.0, reallu too bad you didn't get around to doing it then. Oh well.

**Comment by FelixErnst** [comment]
> The new release errors if one uses `dratBranch = "main"` (or anything other than "gh-pages" or "docs"):
> Luckily the new way seems to be backward compatible.

From my understanding you want to store a CRAN-like repo in a git repo, but instead of using the gh-pages branch, you want to use the `main` branch aka. `master` branch for older repos. Is that correct? @pat-s 

Adding another option for `dratBranch` would be like putting another fix on a fix on a fix. From my point of view a general implementation for the information encoded in `dratBranch` needs to be found for fixing this permanently, which can handle physical locations (like `docs/`) and git repos like(like `gh-pages`).

How about a named `character` of length `1`. The name can be used to differentiate between `git` and `directory` and the value points to the branch or the directory.

**Comment by pat-s** [comment]
> I cannot parse that. Exactly what did you do? Maybe you can add the config snippet you used in your aim is to help others (which I commend).

[Here](https://github.com/cynkra/cynkrathis/blob/c6c2120db4f85faac002ba139fe28eee06d3c1db/R/deploy.R#L61-L71) is the code in which we are using {drat}.
Before v0.2.0 we had 

```r
    withr::with_options(
      c(dratBranch = default_branch, dratRepo = drat_dir))
```

which stopped working with v0.2.0.

> We had the 0.1.8.* pre-release out for almost two weeks for people to do exactly these checks prior to the 0.2.0 release, really too bad you didn't get around to doing it then. Oh well.

I am not watching yours or any other repo for possible requests to release candidates. 
This job should be done by proper tests in my view, not humans.

> From my understanding you want to store a CRAN-like repo in a git repo, but instead of using the gh-pages branch, you want to use the main branch aka. master branch for older repos. Is that correct

Yes. Sources are located directly in the root of the repository in the default branch, e.g. in `src/contrib`. 
We then import this repo with RStudio Connect which refreshes the repo state every 15 minutes and gives us a simple way of serving a minicran repo.

I don't have time to propose any fixes here, I just wanted to outline the problem.
And the fact that allowing only `"docs"` or "gh-pages"` is inconsistent because the latter is a valid/common branch name whereas the former is a directory in the default branch usually. I'd expect either only branch names or no restriction in the first place (which is how it was before v0.2.0 IIRC).

**Comment by FelixErnst** [comment]
> I don't have time to propose any fixes here, I just wanted to outline the problem.

Would you have time to talk about solution acceptable for you? You defined the problem, but a solution to the problem we can come up might not suit you. I don't want this to be a merry-go-round. (Dirk probably has a few cents on this as well)

Can you comment on the solution I proposed? Would that be acceptable, keeping in mind, that you would probably need to change your code slightly as well? Would this be a long-term solution? What would be required for it to become a long term solution?

**Comment by eddelbuettel** [comment]
If it worked before, it should still work for the same use case now: why not continue with a branch `gh-pages` ?

There is also a fair amount of non-standard use (packages we do not use or suggests/importss/depends, a larger commercial product (i.e. RStudio Connect), ...) merits a response from our end -- as Felix hinted, this may be more in your court. `drat` has fairly well defined semantics and still appears to do as it promises.  And as always, a _reproducible minimal verifiable examples_  counts, this does (despite being several messages in) not yet constitute one.   So I fear I may just have to close this ticket unless it is turned into something operational.

**Comment by pat-s** [comment]
> If it worked before, it should still work for the same use case now: why not continue with a branch gh-pages ?

I did not use `gh-pages` before and the new release made `dratBranch = "main"` stop working.
Without a hint in the changelog.
That is all this issue is about.

This is a valid *bug* report in my view.
But I assume your view might differ here again and everything is fine and perfect.

I am not sure why discussions here (and in other repos) often feel complicated but it must be me surely ;)

It might be better to keep such reports for myself in the future and just adapt silently.

> Can you comment on the solution I proposed? Would that be acceptable, keeping in mind, that you would probably need to change your code slightly as well? Would this be a long-term solution? What would be required for it to become a long term solution?

As hinted by the maintainer, my ticket might be invalid and hence all further efforts are probably wasted time :-)

**Comment by FelixErnst** [comment]
@pat-s 

This is this merry-go-round I would like to avoid. We can all get pushed into directions by phrasing and other communication issues, but lets look past that, shouldn't we? If we want to solve this productively, lets meet in the middle.

> This is a valid bug report in my view.

You didn't provide a reproduceable minimal example. Thats a fact, isn't it? The response to that can range from closing an issue without further comment to 50 pages of discussion to just figure out that it was a setup issue. We are here still on a middle ground.
If you would like to continue and help solve the issue, you perceive, please help us perceive it as well. You are active in our community for a long time, so you should know better.

> [...] drat has fairly well defined semantics and still appears to do as it promises

Again, if that is not the case, please help us perceive it. Subjectivity is a problem we all suffer from. I cannot change my pair of eyes, neither can you. Describe what you see and make me see it as well.

PS:
> ...
The tone you are using in the other message does not help anyone solve any issues. Please keep it constructive. Again, you are active for a long time and probably have been on the receiving end as well. If not, please let me know, ...

**Comment by pat-s** [comment]
> This is this merry-go-round I would like to avoid.

I know, I assumed your intentions here already in the first comment. I would have been open leaving the past behind but it seems it does not work (yet) - `(<room for interpretation here>)`.
I don't see much possibility for a constructive discussion here.

I appreciate your constructive feedback.
We can continue discussing this externally (e.g. in a fork or in private) and I am happy to provide feedback there.
Feel free to contact me with the app of your choice if desired.
