### ISSUE TITLE
Replace file.copy with fs::file.copy

### ISSUE THREAD

**Issue by natbprice** [eddelbuettel/drat#127]
The `file.copy` function is very slow (at least on Windows). See here: https://stackoverflow.com/questions/49888078/copying-files-over-network-much-slower-with-file-copy-than-systemmv. 

For a 200 MB package it took about 50 minutes to copy to network file share with `file.copy` and about 1 minute with `fs::file_copy`.

On line 134 in insertPackage.R, I suggest removing:
```
if (!file.copy(file, pkgdir, overwrite = TRUE)) {
    stop("File ", file, " can not be copied to ", pkgdir, call. = FALSE)
}
```
and inserting: 
```
fs::file_copy(file, pkgdir, overwrite = TRUE)
```
Note that `fs::file_copy` does not return a logical.

**Comment by eddelbuettel** [comment]
Interesting.   Now, I have done a fair level of C programming in my life and the copy operation is a (likely atomistic) call to a system library function.  I would encourage you to study what, if anything, `fs` does here to improve over base R and then suggest to R Core to adjust accordingly.  It would also help if we had a bit more empirical support (and maybe profiling evidence?) of where the slowdown comes from.

For `drat`, however, I will likely resist this suggestion.  Narrower dependecies for the core operations are important. If you are truly struck by slower file copy operations via `drat`, mayne you can help yourself by outsourcing the copy operation to `fs` before calling `drat`.

**Comment by natbprice** [comment]
I haven't done any C programming so I can't tell you why it is slow. If you follow the Stackoverflow thread I linked, somebody suggests the issue is that `file.copy` uses a small buffer and references this link: https://github.com/wch/r-source/blob/48499cfb5a9098dc6879a1fb517be3df5c146ab5/src/main/platform.c#L375. 

The fs package sates "It shares the same back-end component as nodejs, the libuv C library, which brings the benefit of extensive real-world use and rigorous cross-platform testing." I don't really have the time/desire to compare the different C implementations of file copying.

**Comment by eddelbuettel** [comment]
Your (edited) statement in the (changed) Subject: was factually not correct.  Drat is not unconditionally slow. So updated.

```r
> dir.create("/tmp/scrap")
> system.time(drat::insertPackage("BH_1.75.0-0.tar.gz", "/tmp/scrap"))
The repository '/tmp/scrap/docs' does not have a top-level 'index.html' file. Consider adding a simple file
to avoid 404 results on the repo. A one-line example is '<!doctype html><title>empty</title>'.
   user  system elapsed 
  0.423   0.067   0.455 
> file.info("BH_1.75.0-0.tar.gz")$size
[1] 11881161
> 
```

455 milliseconds elapsed for a 11.88mb file is not so shabby (and amounts to 26.11 mb/sec).  It all depends on the OS, and we know Windows does not exactly shine here, and networked drives even less.  Little that R can do about it; if `fs` gives you a workaround maybe you should (as I suggested) look into getting it more widely used.

**Comment by natbprice** [comment]
Since this is a serious issue preventing me from adding large R packages to my existing drat repo, you are opposed to incorporating the simple workaround I described, and it is unlikely to be resolved in base R anytime soon, I have created a fork based on `fs::file_copy` for my own use. Maybe it will help somebody else who is experiencing similar issues:

**Fast drat**: https://github.com/natbprice/fdrat

**Comment by eddelbuettel** [comment]
Simple advide: consider not relying on Windows if you care about performance.

**Comment by natbprice** [comment]
By the way, I have not tested the speed of fdrat with network storage on OS's other than Windows. I will leave it up to you to confirm the extent of the performance issues.

**Comment by eddelbuettel** [comment]
Gosh are trying to be extra irritating?

```
> system.time(system("scp BH_1.75.0-0.tar.gz rob:/tmp"))
BH_1.75.0-0.tar.gz                                                     100%   11MB 469.0MB/s   00:00    
   user  system elapsed 
  0.031   0.010   0.222 
> 
```

That's over wifi.

I
