### ISSUE TITLE
pruneRepo fails with for package type mac.binary.big-sur-arm64

### ISSUE THREAD

**Issue by botanize** [eddelbuettel/drat#134]
While `insertPackage` became mac.binary.big-sur-arm64 aware, it looks like `pruneRepo` and `archivePackages` did not.

It's currently failing for me when attempting to match the type parameter because `mac.binary.big-sur-arm64` isn't included in the valid options, here:
https://github.com/eddelbuettel/drat/blob/b3d3fe1555c0d49b665ac4efd30599a792905d42/R/pruneRepo.R#L158

## proposed solution
Change 

```r
type = c("source", "binary", "mac.binary", "mac.binary.el-capitan",
                               "mac.binary.mavericks", "win.binary", "both")
```

to

```r
type = c("source", "binary", "mac.binary", "mac.binary.big-sur-arm64",
                               "mac.binary.el-capitan", "mac.binary.mavericks", "win.binary", "both")
```

For the affected lines in pruneRepo.R and archivePackages.R.

I'm happy to submit a PR and update `testArmBinary.R` to test archive and prune functionality.

**Comment by eddelbuettel** [comment]
Good catch.  It is possible that we overlooked this when adjusting the inserter.

As you have the ability to test this locally would you mind setting up a PR you could test?  I cannot easily 'mock' being on such a macOS variant.
