### ISSUE TITLE
minor typo

### ISSUE THREAD

**Issue by sadchla-codes** [eddelbuettel/drat#136]
Minor typo with `converntion` instead of `convention`, although it doesn't really affect the code. (nice package!)
![drat_typo](https://user-images.githubusercontent.com/112789549/196838236-d878e073-e09a-4344-b787-2c00772985d8.png)

**Comment by eddelbuettel** [comment]
Had to `grep` where you spotted this but yup, the DratFAQ vignette has that typo and per `git blame` since 2015 when I wrote that.  Ouch.  Will fix now.  Thanks for the heads-up!

**Comment by sadchla-codes** [comment]
Thank you!
