### ISSUE TITLE
Possible discrepancy between where drat and CRAN places binaries when .Platform$pkgType is "mac.binary.big-sur-x86_64"

### ISSUE THREAD

**Issue by arnejohannesholmin** [eddelbuettel/drat#138]
Hi,

Thank you for a brilliant R package.

I have however an issue I would like to check on. I am a bit confused about the folder in which binaries are placed by drat on macOS. On my Intel Mac I get 

```
.Platform$pkgType
[1] "mac.binary.big-sur-x86_64"
```

which is also reflected in 

```
utils::contrib.url("https://cloud.r-project.org", type = "binary")
[1] "https://cloud.r-project.org/bin/macosx/big-sur-x86_64/contrib/4.3"
```

This is the path used by install.packages(), as far as I understand.

However, in my [repo](https://github.com/StoXProject/testingRepo/tree/gh-pages/bin/macosx/contrib/4.3) generated by drat the macOS binaries for R 4.3 are placed in 

"bin/macosx/contrib/4.3"

I have not had the chance to test where drat places macOS binaries for the Apple silicon (M1/M2) Macs, but at least "mac.binary.big-sur-arm64" is listed as one of the DRAT_BINARY_TYPES in the file 

[archivePackages.R](https://github.com/eddelbuettel/drat/blob/master/R/archivePackages.R)

Could it be that drat should place the Intel Mac binaries in a folder "bin/macosx/big-sur-x86_64/contrib/4.3" instead of "bin/macosx/contrib/4.3"?

**Comment by eddelbuettel** [comment]
That is very much possible, and as I would need your help in correcting / tuning this.

There is [a moderate amount of code](https://github.com/eddelbuettel/drat/blob/master/R/insertPackage.R) in the package trying to find these paths, dependending on both the system / OS / cpu / version / ... and it is possibly that we need an update for R 4.3.0 on macOS with big-sur.   Can you take a poke at updating / correcting this ?

**Comment by arnejohannesholmin** [comment]
So, I cloned this repo and made a copy in our [organization](https://github.com/StoXProject) (got confused about forking), made the following two changes to the [insertPackage.R](https://github.com/eddelbuettel/drat/blob/master/R/insertPackage.R) file, and voila, I got the correct [bin/macosx/big-sur-x86_64/contrib/4.3](https://github.com/StoXProject/testingRepo/tree/gh-pages/bin/macosx/big-sur-x86_64/contrib/4.3) folder:

1. On line 259, change 

`} else if(pkginfo["osxFolder"] %in% c("mavericks","el-capitan","big-sur-arm64")) {`

to 

`} else if(pkginfo["osxFolder"] %in% c("mavericks","el-capitan","big-sur-arm64", "big-sur-x86_64")) {`


2. Change lines 311 - 315 

```
osxFolder <- switch(fields["OSflavour"],
                        "x86_64-apple-darwin13.4.0" = "mavericks",
                        "x86_64-apple-darwin15.6.0" = "el-capitan",
                        "aarch64-apple-darwin20"    = "big-sur-arm64",
                        "")
```

to lines 311 - 316

```
 osxFolder <- switch(fields["OSflavour"],
                        "x86_64-apple-darwin13.4.0" = "mavericks",
                        "x86_64-apple-darwin15.6.0" = "el-capitan",
                        "aarch64-apple-darwin20"    = "big-sur-arm64",
                        "x86_64-apple-darwin20"     = "big-sur-x86_64",
                        "")
```

**Comment by arnejohannesholmin** [comment]
At first I did not see a need for a PR, but then I realised that there were more changes required that the two listed above (function argument defaults and documentation), and I also added a small package and a test as you suggested [PR 139](https://github.com/eddelbuettel/drat/pull/139). It passed R CMD check locally, so hopefully I did not mess up anything.

**Comment by eddelbuettel** [comment]
Fixed in #139 -- thanks so much!

I'll look into a release to CRAN 'real soon'.

**Comment by eddelbuettel** [comment]
Hey @arnejohannesholmin we are looking _mostly_ really good.  I merged, rolled the version, then forgot I actually check the version in DESCRIPTION against the one in NEWS, updated at force pushed.  

At r-universe, which as a default runs a broader set than we do in CI, we do see an error with macOS and 'oldrel' ie 4.2.
Would have be able to get hold of R 4.2 on macOS to take a look?  It may be as simple as a test (implicitly ?) assuming R 4.3.* in the big-sur test so maybe we should make sure that that test only runs when R is 4.3?

Screenshot of the state of the world:

![image](https://github.com/eddelbuettel/drat/assets/673121/79064d34-d1a8-446d-bda2-7030af3a6683)

URL of the run is https://github.com/r-universe/eddelbuettel/actions/runs/4973726533/jobs/8899774367

**Comment by arnejohannesholmin** [comment]
Hi, 

I ran R CMD check on 4.2.3 and got the same error you showed from r-universe. However, I am not sure that it is related to the added test for mac.binary.big-sur-x86_64. When I ran R CMD check on the latest [commit](https://github.com/eddelbuettel/drat/commit/7db7900830ef61ad7d9e12b36374dec05d5a8f40) before I started poking around, it failed with the same error. It seems that when in R 4.2.3 there are 7 rows in `repoinfo` on line 123 of [skeleton_git2r.R](https://github.com/eddelbuettel/drat/blob/master/tests/skeleton_git2r.Rhttps://github.com/eddelbuettel/drat/blob/master/tests/skeleton_git2r.R) but only 6 rows (as expected by the test) on R 4.3.0. 

When I tried disabling line 131 R CMD check ran without any errors in R 4.2.3. 

I am not sure I understand why we get 7 and not 6 rows in R 4.2.3. The `repoinfo` table has an extra second row that seems identical to the following row except for that the type is "binary" and not "mac.binary". So it seems we get a copy for some reason. 

It is tempting to add a condition for R 4.2 allowing 7 rows, which I tried locally and it worked.

**Comment by eddelbuettel** [comment]
Oh good point, good point -- that may have been older than your PR!  Sorry for implying otherwise.

Those tests are quite comprehensive and also quite _incomprehensible_  :grinning:   I didn't write them, and sweated debugging them too.  I think I will glance at your PR, like merge it and if r-universe (which gives me multi-release tests for free, as it does to everybody else ...) passes I think we can ship this version to CRAN.

Thanks for your diligence here.  It helps a lot with the macOS side I cannot really cover.

**Comment by arnejohannesholmin** [comment]
Yes, I made a new PR with the 7 rows for R 4.1 and 4.2. Hope it works.

**Comment by eddelbuettel** [comment]
I think at this point I just trust you and wait the hour or so it takes for r-universe to catch up.  Fingers crossed!

**Comment by eddelbuettel** [comment]
Boo-hoo.  Now windows-oldrel no longer likes us:

![image](https://github.com/eddelbuettel/drat/assets/673121/05378f49-79a5-4508-9f7e-30ea80149087)

Per https://github.com/r-universe/eddelbuettel/actions/runs/4985115061/jobs/8924384187

**Comment by eddelbuettel** [comment]
So I punted in https://github.com/eddelbuettel/drat/commit/79af2e9149c07f873029376a562dfe93833fb25e and turned a `stop()` into a `warning()`.  Should probably have done that earlier also with the one you fixed. Now all is good:

 
![image](https://github.com/eddelbuettel/drat/assets/673121/6a5c6a26-8cf5-4fd9-ab09-04a1e23e79a1)
