### ISSUE TITLE
Package building

### ISSUE THREAD

**Issue by csgillespie** [eddelbuettel/drat#14]
Would you be interested in a `build` function? I'm thinking something like:

```r
build <- function(pkg_dir=".", check=FALSE){
  if(check) # R CMD check pkg_dir
  # Next
   #Call R CMD build pkg_dir
   return(pkg_dir)
}
```
Then in the `insert` function,  if the `file` argument points to a directory, call `build`.

**Comment by eddelbuettel** [comment]
Hm.  I work on the command-line as much as I work at the R prompt.  

So to me 'R CMD build' is no real cost, or if it were I'd add another littler script.  Also, someone already mentioned a similar devtools function [I don't use devtools myself] which does and returns the tarball as a argument, ready for insertion by drat.

The last need for a help was something I stuck into `inst/scripts/` of drat:  given a GH repo, create a tarball.  I am using that (very slowly) with the [GitHub-hosted R Repo](https://github.com/ghrr) and its drat.

Also, `build()` would be hard to get right.   

What do you think?

**Comment by csgillespie** [comment]
I don't really use `devtools`, but I've just had a quick look at the `build` function and agree that it would be silly to reinvent that particular wheel.

I think the natural thing would be to detect 

1. If the argument was a directory, call `devtools::build`
1. If the argument was a github repo, clone in a tmp dir, then call `devtools::build`

The benefit of `devtools` would be that the build function would work on windows (provided the dependencies are met). The downside is it's another dependency. One option is just to make `devtools` a suggested package.

**Comment by eddelbuettel** [comment]
Can't do as I'd then depend on devtools.  There are lines I don't cross ;-)

We can document it though.  Lots of people do like devtools, and having its `build()` invoked may be natural to them.

**Comment by csgillespie** [comment]
Okey dokey.

One more thing. It should be straightforward to add an `insertPackage` call to a `.travis` script. That way the drat repo will always be up-to-date, *but* only if the package passes all tests. Does this sound sensible? It should solve your GH repo problem, not require any additional (drat) code and not depend on `devtools`.

**Comment by eddelbuettel** [comment]
That may be doable, though 'git push' requires authentication.  And Travis builds often repeat while then Version: number does not change, so you would not exactly have consistency of "one version, one build, one tarball".  

I also really like where git2r allows us to go from R.  Not sure yet about the password / ssh issue, but @stewid is looking at that and he and I have exchanged some note.

**Comment by csgillespie** [comment]
I'll experiment with travis and let you know if I get it working. I'll try and write up an intial workflow with `devtools::build`. Thanks

**Comment by eddelbuettel** [comment]
Thumbs up!   Some folks are still very confused about drat so the more usage stories (on the blog, and/or as vignettes) we have the better!

**Comment by csgillespie** [comment]
For info, I've created an example of automatically updating a `drat` repo via a travis build (https://github.com/csgillespie/dratTravis)

**Comment by eddelbuettel** [comment]
That is awesome.  Shall we turn this into a quick blog post, joint or guest post by you?

**Comment by csgillespie** [comment]
I'm happy for a joint post. How should we proceed?

**Comment by eddelbuettel** [comment]
Markdown works great, and for iterating back and forth we could just email, or share via Dropbox file. I tried Google Docs once and that did not work so well with the .md content.

What you have at the dratTravis is already pretty good and I linked to it from the drat page.

**Comment by csgillespie** [comment]
What about creating a wiki page, either on the drat repo, or on a short-lived, newly created repo. After the post is published on your blog, we just delete the page/repo.

**Comment by eddelbuettel** [comment]
I am somewhat hesitant to add it somewhere here is a transient matter.  So I don't like the repo-for-a-blog-post all that much.   We could just email it too...

**Comment by eddelbuettel** [comment]
We could also just aim straight for a vignette, and happen to also co-post the vignette as a blog post. So in that case we'd just start with a PR.  Better?

**Comment by csgillespie** [comment]
Sounds good. Let's go with a vignette. I'm travelling for the next couple of weeks, of progress may be slow.

**Comment by eddelbuettel** [comment]
No worries.  Ok if I import (parts of) your README.md as a starting point?  

I think I'll do the same with some of the other blog so that we have a few (short) vignettes to go from; better content will hopefully over time replace poorer one.

**Comment by csgillespie** [comment]
Go for it. Blog posts are good initial advertisements, but vignettes last a bit longer.

**Comment by eddelbuettel** [comment]
:+1: and done!  

We'll revise going forward.
