### ISSUE TITLE
[windows] Create repository using local server 

### ISSUE THREAD

**Issue by emanuele-depaoli-sdg** [eddelbuettel/drat#143]
I'm trying to create a repository using a local server in Windows. 
I've forked the sample repository from `https://github.com/drat-base/drat` and put it in wwwroot folder `C:/inetpub/wwwroot/` 
I can insert packages with `drat::insertPackage("tst_pkg_1.0.tar.gz", "C:/inetpub/wwwroot/drat/docs")`, but I can't install them. I tried

```
drat::addRepo("tst_repo", "C:/inetpub/wwwroot/drat/docs")
install.packages("tst_pkg", repos = "tst_repo", type = "source")

```
The error is

```
Warning in install.packages :
  unable to access index for repository C:/inetpub/wwwroot/drat/docs/src/contrib:
  cannot open URL 'C:/inetpub/wwwroot/drat/docs/src/contrib/PACKAGES'
Warning in install.packages :
  package ‘tst_pkg’ is not available for this version of R
```

Do you have any clue why it is not working? 
Thanks in advance.

**Comment by eddelbuettel** [comment]
I do not know from the logged output shown what your issue is.  Can you trace it step by step using standard R debugging (_i.e._ use `browser()` and step through, or add `print` statements or ...) so that we can fix this?

`drat` does work with any server running / exposing a file access method `install.packages()` can support.  We often use GitHub Pages 'because it is there' but I have used a local (and more private _i.e._ mostly for own use) directory on my server for many years.

**Comment by eddelbuettel** [comment]
Thank you that is helpful!  From reading the line I suspect it may be `type="source"` that creates the trouble for you.  Does it work if you use `type = "binary"` and/or let R use the default?  Are you injecting binary or source packages?

Can you cook up a small test example as is done in the unit test directory?  That would help as I do not have (easy) access to Windows.

(And if my suspicion is correct this is more of an issue of `drat` on Windows in general than with the local serving. There may never have been that many windows users and not many people use windows as a server. Of course one can so we should fix this.  Appreciate your help.)

**Comment by emanuele-depaoli-sdg** [comment]
I made it work writing the repo explicitly:
`install.packages("tst_pkg", repos = "http://127.0.0.1/drat/docs", type = "source")` 

Apparently `drat::addRepo("tst_repo", "http://127.0.0.1/drat/docs")` is not working in my case.

**Comment by emanuele-depaoli-sdg** [comment]
When `install.packages()` calls `available.packages()`, type is set to "source" correctly. The call is `available.packages(contriburl = "tst_repo/src/contrib", method = NULL, ...)`

**Comment by eddelbuettel** [comment]
I am sorry but we are not making real progress here.  If you can work out a _change to the source code of the `drat` package_ and provide what GitHub calls a pull request I can review it.  I cannot code a solution for you as I do not have a Windows machine.  Sorry.

**Comment by eddelbuettel** [comment]
Closing for lack of follow-up.
