### ISSUE TITLE
Possible to install from github release?

### ISSUE THREAD

**Issue by pschloss** [eddelbuettel/drat#145]
I like the [suggestion](https://journal.r-project.org/articles/RJ-2017-026/) of using {drat} to host a data package on GitHub that goes along with a stand alone package on CRAN. Unfortunately, my bundled and compressed package file is about 150 MB, which means it cannot be hosted on GitHub since there's a 100MB limit per file. My understanding is that a release on GitHub can be up to 1GB. Is there any way or plan to use the benefits of {drat} but to install the package from a release?

**Comment by eddelbuettel** [comment]
Someone would need to code it up, possibly by reusing what @cboettig has done in [piggyback](https://cran.r-project.org/package=piggyback), and contribute.  I myself have no plans or needs to do so.  So with that I will close as 'not planned'.  If you want to and can work on this by all means please reopen.
