### ISSUE TITLE
Remove packages?

### ISSUE THREAD

**Issue by piccolbo** [eddelbuettel/drat#18]
Hi, I was wondering if there is a way to remove a package. For instance, I cloned drat and I have several drat packages in my gh-pages branch. But I do not think I should host it if I don't intend to keep it up to date. Also one may want to remove ancient copies of a package, or versions that have been found in breach of some arcane policy. I thought that a git rm followed by a commit and push  would do it, but one needs to open a shell and the PACKAGES file would become inaccurate. Am I missing something or could this be a reasonable new feature proposal? Thanks

**Comment by eddelbuettel** [comment]
Yes see the not-quite-done function [pruneRepo](https://github.com/eddelbuettel/drat/blob/master/R/pruneRepo.R). 

I was waiting on @stewid to add `rm` functionality to [git2r](https://github.com/ropensci/git2r) and awesome as he is he has long added it.  As soon as that version hits CRAN I will use that in a package update.

Until then you can just feed the output of `pruneRepo()` into a manual `git rm` loop.

Thanks for your interest in drat.

**Comment by eddelbuettel** [comment]
Also note that cloning drat is _one_ of several ways to set up a `gh-pages` branch with `src/contrib`.  If you'd rather do it by hand, fine.   As for `PACKAGES` "become inaccurate": Just re-ran the (base R) function to regenerate it, or even easier, do another `insertPackage()` call.

**Comment by piccolbo** [comment]
I guess I should have just read the code -- it's not that much -- but reading pruneRepo left me a little baffled, now it makes sense knowing that it doesn't have any side effects quite yet. Thanks for the clarifications.

**Comment by eddelbuettel** [comment]
My bad as it is mostly undocumented. I just knew that R itself already had that solved (because a PACKAGES file only ever has the newest, so it knows how to skip).  Reading a directory is easy enough so that was straightforward.  But not released yet...

If you have other API / helper suggestions let me know.  Better yet pull-request them in ;-)
