### ISSUE TITLE
Unable to access index for repository (windows)

### ISSUE THREAD

**Issue by smbache** [eddelbuettel/drat#22]
I am trying to evaluate whether `drat` is useful for distributing packages internally on a shared windows network, and I am running into trouble when trying to install inserted packages.

I did the following:

1. Built a source package
2. `drat::insertPackage("pkg_1.0.0.tar.gz", "S:/path/to/drat")`
3. In another session, `drat::addRepo("localRepo", "S:/path/to/drat")` and `install.packages("pkg", type = "source")`

I get the warnings:

```
Warning in install.packages :
  unable to access index for repository S:/path/to/drat/src/contrib
Warning in install.packages :
  unable to access index for repository S:/path/to/drat/src/contrib
Warning in install.packages :
  package ‘pkg’ is not available (for R version 3.2.0)
```

The folder structure created contains:
```
S:/path/to/drat
  /src
    /contrib
      PACKAGES
      PACKAGES.gz
      pkg_1.0.0.tar.gz
```

What am I missing? Or is there a bug (most likely me)?

**Comment by eddelbuettel** [comment]
You probably want the github version right now.  

Version 0.0.3 on CRAN has _no_ Windows support; the unreleased version has some thanks to @JanSchulz.  Adding OS X is next, but I need help as I have no OS X box.

We need what you do above down into two steps. Step 2 I do all the time at work and home.  Do inspect PACKAGES and PACKAGE.gz -- they should contain the info for `pkg`.

Step three should work.  But the errors are add.  After `drat::addRepo()`, what does `getOption("repos")` show?

**Comment by smbache** [comment]
Ahh, ok, I'll give the GitHub version a try.

The `PACKAGES` file looks correct. `PACKAGES.gz` includes a file that looks identical to `PACKAGES`.

`getOption("repos")`gives somthing like:
```
CRAN                       localRepo 
"http://cran.rstudio.com"  "S:/path/to/drat"
```

**Comment by smbache** [comment]
I just tried the GitHub version, repeated the process described above, and I get exactly the same warnings.

**Comment by eddelbuettel** [comment]
Let us please decompose this step by step.  At work we both push and pull to a local repo as you do.

So for completeness do
```{.r}
AP <- available.packages()      # with the drat repo set
AP[ AP[,"package"]=="pkg", ]   # to inspect the record
```
so that we can confirm that R sees the package.   As for the warnings, we need to trace back what R.  I never run this from within R (force of habit) but via [install.r](https://github.com/eddelbuettel/littler/blob/master/examples/install.r) -- but that still just call `install.packages()`.  There must be something we are missing -- you do set `type="source"`.  Maybe it still wants `type="binary"` on Windows?   Any insighs on the Windows side, @JanSchulz ?

**Comment by smbache** [comment]
Already there is the issue:

```R
> AP <- available.packages()
Warning: unable to access index for repository S:/path/to/drat
```

**Comment by smbache** [comment]
So, 

1. `insertPackage("pkg_1.0.0", "C:/drat")`
2. `addRepo("local", "file:C:/drat")`
3. `install.packages("pkg")`

works. However, if I have a space in the path, it won't work. Inserting is fine, but even with various quoting options, I can't get 2. to work (in the sense that 3 will work :)).

Note that in 2. it was important to have `file:` (not `file://`) to make it work.

**Comment by eddelbuettel** [comment]
Thanks for that, Stefan!  This makes perfect sense.

We also learned the hard way and over several iterations to protect path expression when we need them inside the Rcpp tooling.  I will take a good look at the (short) code and try to add that protection.  May just be `sQuote{}` wrapping.   

Also, yes, for basic 'to local network storage' and just tar.gz, the CRAN version is sufficient.  I mistook your first email as requiring binary support.  Lastly, would you want/need binary support, and did R croak when you had no `bin/windows/$VERSION` in the repo?

**Comment by smbache** [comment]
On phone now, so brief. 

Yeah I could have made that more clear. Binary support would be nice to have - but not necessary. 

Indeed, if I don't specify type="source" R will break when it can't find the correct directory and file. 
 
Also, I had problems installing anything else after addRepo as R would now only look there. Maybe my last session had an issue, had no time to try more. Will play with it again tomorrow.

**Comment by eddelbuettel** [comment]
Really appreciate the feedback and testing!

**Comment by smbache** [comment]
And thanks for the prompt replies. Giving an internal course in a few days and wanted to figure out how best to distribute things... This seemed like a good solution.

**Comment by csgillespie** [comment]
@smbache Just a comment. Drat is excellent for internal courses. I've also coupled it with miniCran. This now allows me to carry the course package (and all associated packages!) on a memory stick.

@eddelbuettel Sorry for the noise - please don't shout.

**Comment by eddelbuettel** [comment]
Seemed? Past tense? Already given up on?  :-)

If you can control a webserver to point at `S:/path/to/drat`, I have found that pretty flawless.  So we write to a network on repo addition, but then get the packages onto machines via http.  Removes the `file:` vs `file://` hurdle I apparently underdocumented.

I briefly looked into this.  `shQuote()` is not what I wanted, and `normalizePath()` may be. Can you try `dir(normalizePath(somePath))` and see if that works without barking?

@csgillespie :+1: thanks -- what is there in miniCRAN that drat misses?  Anything we should carry over?

**Comment by csgillespie** [comment]
[miniCran](http://cran.r-project.org/web/packages/miniCRAN/index.html) is a handy little package. Essentially, 

 * miniCran gets all dependencies for your package and downloads them from CRAN (Binary  & source)
 * I then add all the dependencies to my `drat` [repo](https://github.com/rcourses/drat/tree/gh-pages/bin/windows/contrib/3.2)

Now when I run a course, even if the internet goes down, I can still install my course package via a USB stick with all associated dependencies.

> what is there in miniCRAN that drat misses? 

Automatically getting dependencies from CRAN (and other places).

> Anything we should carry over?

I think the two packages go hand in hand. Essentially, I have  function adds dependencies to my (github) drat repo. I imagine that other users would find that useful. You could make it a suggested package and include a little helper function. Or just give an example. I'd be happy to contribute to either.

**Comment by smbache** [comment]
"Seemed" was a mistake; still seems ;)

I'll look more into this tomorrow. Also the minicran idea..

**Comment by eddelbuettel** [comment]
@csgillespie Oh, yes, the 'no network' aspect for offline work.  

drat, at least for now, always assumes CRAN is reachable :)   We could easily write a 'dependency walker' that makes a drat self-sufficient.  I have no view on whether this would be desirable, or if the cooperation with miniCRAN is natural enough.  Let's play it by ear -- if you have code snippets that could start as contributed examples (like by 'get this from github and build a tarball script') then we could start there.  If needed it could always grow into a real function.

@smbache Noted :)

**Comment by csgillespie** [comment]
@eddelbuettel OK, I'll try and write up an example in the future.

**Comment by eddelbuettel** [comment]
@stefanbache: I just did some quick tests:
+ `c:/temp/temp folder/` works
+ `c:/temp/tempfolder/` works too
**but** in both cases did I need the `file:` prefix you also pointed out.  This is seems to be more of a documentation than code issue.   Do you agree based on your tests?

**Comment by smbache** [comment]
I had a path with space in which did not work. But it also contains a #, something like S:/# path/to/drat

I can check more soon

**Comment by smbache** [comment]
I tried a few things again; here are the results, sorry for the mess:

```R
drat::insertPackage("pkg_1.2.0.tar.gz", "C:/test/R/drat")
drat::insertPackage("pkg_1.2.0.tar.gz", "C:/test/R R/drat")
drat::insertPackage("pkg_1.2.0.tar.gz", "C:/test/# R/drat")

# WORKS!
drat::addRepo("localRepo", "file:C:/test/R/drat")
install.packages("pkg", type = "source")

# Restart session; DOES NOT WORK!
drat::addRepo("localRepo", "file:C:/test/R R/drat")
install.packages("pkg", type = "source")

Warning: invalid package 'C:/test/R'
Warning: invalid package 'R/drat/src/contrib/pkg_1.2.0.tar.gz'
Error: ERROR: no packages specified
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-32~1.0/bin/x64/R" CMD INSTALL -l "C:\Program Files\R\R-3.2.0\library" C:/test/R R/drat/src/contrib/pkg_1.2.0.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘pkg’ had non-zero exit status


# Restart session; DOES NOT WORK!
drat::addRepo("localRepo", "file:C:/test/# R/drat")
install.packages("pkg", type = "source")

Warning: invalid package 'C:/test/#'
Warning: invalid package 'R/drat/src/contrib/pkg_1.2.0.tar.gz'
Error: ERROR: no packages specified
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-32~1.0/bin/x64/R" CMD INSTALL -l "C:\Program Files\R\R-3.2.0\library" C:/test/# R/drat/src/contrib/pkg_1.2.0.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘pkg’ had non-zero exit status
```

**Comment by eddelbuettel** [comment]
Hm, I think the second one (`c:/test/R R/drat`) worked for me (`c:/temp/temp folder/`).  Not sure why it would park for you.

You can just test the sequence `addRepo(....); AP <- available.packages()` as `available.packages()` needs the `PACKAGES` file too.

Can you try `drat::addRepo("localRepo", normalizePath("file:C:/test/R/drat")); AP <- available.packages()` and see if that helps?   Otherwise I am out of ideas...

Dirk

**Comment by eddelbuettel** [comment]
@jjallaire: Sorry for the cross-thread note (and don't feel compelled to read up on all of this) but I checked and `Rcpp::R/Attributes.R` just bails when it sees a space in a path on Windows:

```{.r}
    # validate that there are no spaces in the path on windows      
    if (.Platform$OS.type == "windows") {
        if (grepl(' ', basename(file), fixed=TRUE)) {
            stop("The filename '", basename(file), "' contains spaces. This ",
                 "is not permitted.")
        }
    }
```

I think I may borrow this here.  Nothing good seems to come from trying to access repos with a space in the path.   Thoughts?

**Comment by jjallaire** [comment]
Yes, I completely agree here.

On Fri, May 22, 2015 at 9:46 AM, Dirk Eddelbuettel <notifications@github.com

**Comment by smbache** [comment]
Sort of -- except I have a path I can do nothing about, so that is a pain...

**Comment by smbache** [comment]
The normalizePath did not work :(

**Comment by eddelbuettel** [comment]
@jjallaire Thank you, and so it has been decided :)

@smbache What about my earlier suggestion to layer http over it?  If you can admin a webserver config somewhere -- and $DEITY knows maybe even Yihui's servr can be abused for that, I just use Apache straight-up as I live on Linux here -- then you can serve the files over http.  As we saw, _inserting_ actually works.

**Comment by smbache** [comment]
I now tried servr to serve the files; unfortunately I can't get it to work; while I am able to browse to the files via a browser at the specified hostname, `install.packages` just hangs.

**Comment by smbache** [comment]
Oh -- my bad; it did work. But response time was veeeeeery slow. Browsing is snappy enough, I have no idea why that should take so long. Maybe 2-3 minutes with a small package.

**Comment by eddelbuettel** [comment]
I was half-joking when I said servr; there may well be limits to what it can do as it is, as far as I know, still running as a R program.

But maybe you could run a real webserver?
