### ISSUE TITLE
Functions documented but no mention they're not exported

### ISSUE THREAD

**Issue by Mullefa** [eddelbuettel/drat#26]
Are the following functions not exported intentionally?

- `getPathForPackageType()`
- `identifyPackageType()`

If so, the documentation is misleading.

**Comment by eddelbuettel** [comment]
They are contributed and where initially internal only.  We could export them -- this fell to the wayside for the most recent release.

**Comment by Mullefa** [comment]
In my humble opinion I think either the function should be exported and the documentation available to the user, or the function should not be exported and there should be no documentation available to the user. In this case I would vote to not export them as without the package is incredibly streamlined.

**Comment by eddelbuettel** [comment]
Yes, as I said, that needs to be revisited.  Not exactly the biggest problem in the world and we can keep this issue open...

**Comment by eddelbuettel** [comment]
I am closing this.  There is no issue (in `R CMD check` complaining sense) in having _more_ documentation.   The functions aren't exported as they are not first-class user facing.
