### ISSUE TITLE
Higher-level function for downloading package and inserting?

### ISSUE THREAD

**Issue by Mullefa** [eddelbuettel/drat#27]
I don't know if this is in the spirit of the drat, but a utility function for downloading a package (of a specific version) and inserting it into the drat repository would be _very_ convenient.

**Comment by eddelbuettel** [comment]
Did you see [inst/scripts/git2targz.sh](https://github.com/eddelbuettel/drat/blob/master/inst/scripts/git2targz.sh)?

**Comment by Mullefa** [comment]
Yeah, agree with not adding devtools. That package (as nice as it is) brings a lot of friends to the party.

I've created a function `drat_install()` in [virtualenv](https://github.com/Mullefa/virtualenv) which roughly provides this functionality (although it no doubt has some bugs to fix). The functioninstalls a package into the user's local library, and also inserts the source into the drat repository ready to be pushed to github. I'll probably consider being able to push the updated drat repository to github as part of the function.

**Comment by eddelbuettel** [comment]
Let's keep talking!  I glanced at virtualenv after you first emailed about and liked it (but you need a better, and different, name ...) 

There are plans for a new and no-depends devtools to be written. We'll see.  Til then, we will try to keep the party small :)

**Comment by Mullefa** [comment]
Haha sure. Open to suggestions regarding the name. I've sketched what a 'happy path' would like for installing a package into the <insert decent name> , then inserting it into the local drat repo, adding and committing the changes, and pushing to github. Clocking off now, but will give it more thought tomorrow.

**Comment by richfitz** [comment]
It's possible that I'm the "someone else" here, with this package https://github.com/richfitz/drat.builder (with feedback and testing from @cboettig).  Still surprisingly difficult to get this behaving well with things like vignette building (requires installation of dependent packages) and handling things like packages in subdirectories of git repos.

No longer has a devtools dependency, and soon won't have a git2r one because in the end command line git was needed.

**Comment by Mullefa** [comment]
@richfitz some of the stuff in here looks cool! I have been working on a related package [virtualenv](https://github.com/Mullefa/virtualenv). It's a package to facilitate using isolated projects in R. It's fairly new, but we are using it with success in production at my company.

Currently it does two conceptually different things: isolated projects, and package management. I wonder whether the two packages we have created can be refactored into two packages which solve these problems respectively? Analogous to virtualenv and pip for python if you're familiar with them? Or because the two tasks go hand in hand, whether the two packages can be combined at some point in the future?

Give me an email if this sounds like your bag.

**Comment by eddelbuettel** [comment]
There in fact a number of projects like that floating around R, from packrat to switchr and others.

But seeing that this has little to do with drat at the moment, I am going to close this.  When you guys find either a deficiency in drat, or a straightforward extension, please do file a PR.
