### ISSUE TITLE
Can drat work with github enterprise?

### ISSUE THREAD

**Issue by Mullefa** [eddelbuettel/drat#28]
I have created a repository on github enterprise, but am unable to install anything from it yet. I imagine (hope) it may be possible to install packages from the enterprise repository, by passing the correct value to the `extra` argument in `download.file()` (via the `...` argument of `install.packages()`), however, I haven't had any success so far.

**Comment by eddelbuettel** [comment]
I do not have access to GH Enterprise.  

"All we do here"  is to rely on the fact that if user `Mullefa` creates a repo `drat` with a `gh-pages` branch, the URL `http://Mullefa/github.io/drat` will serve content.  So we place the repo there, and make use of the implied-name drat -- so `addRepo("Mullefa")` work.   

You'd have to research this on your end.  Do report back though :)

**Comment by Mullefa** [comment]
OK. I'm in talks with someone from github, so will update this issue when I get a conclusive answer.

**Comment by hadley** [comment]
I suspect all that is needed is an additional parameter to `addRepo()` (or perhaps a new function) that allows you to override `github.com` with the host name for your internal github enterprise server.

**Comment by eddelbuettel** [comment]
You mean like the existing second argument `alturl` in `addRepo(account, alturl)` ?   

We use that at work all the time with a local repo a la `addRepo("localRepo", "http://Rserver/R")` where Rserver is a DNS entry to one of the servers.

**Comment by hadley** [comment]
Yes, exactly - it doesn't seem like anything else is neccesary.

**Comment by Mullefa** [comment]
Apologies, I should have been clearer when I first raised the issue. 

I am able to set the url of the drat repo on github enterprise, but I am not able to install packages from it. If I try and `curl` a `tar.gz` file in the drat repo from the command line I get a redirect response (I'm guessing because the request is not authenticated). I imagine this is related to what's preventing me from installing packages from the drat repo. I'll try and resolve the problem and post some more information when I'm back at work on Monday.

**Comment by eddelbuettel** [comment]
Any updates?  Shall we leave this open, or close it with or without resolution?

**Comment by Mullefa** [comment]
Close without resolution :(

I tried for quite a while to get this to work and couldn't; and any chance of progress is now not possible as I have no longer have access to github enterprise.
