### ISSUE TITLE
Archive old source rather than prune

### ISSUE THREAD

**Issue by leeper** [eddelbuettel/drat#29]
My impression is that when a new version of a package is added, the older versions are removed. Shouldn't they be added to a CRAN-style `/Archive/PkgName` directory instead (at least optionally)?

**Comment by eddelbuettel** [comment]
Nice idea, I like it, particularly as an option.  Now someone has to code it ...

**Comment by leeper** [comment]
Would you accept it as an option to `insertPackage`? Something like:

```R
insertPackage(file = "pkg_ver.tar.gz", action = c("mask", "prune", "archive"))
```

So, `action` could be "mask" (the current default; do nothing, just add), "prune" (call `pruneRepo`), or "archive" (a new function that moves the old package version(s) into the Archive and creates an Archive directory if one doesn't exist).

I might be able to get to it this weekend sometime.

**Comment by eddelbuettel** [comment]
Yes, I surely would. I like that -- clean extension of current behaviour.
