### ISSUE TITLE
deploy.sh can reveal Github access token on git errors

### ISSUE THREAD

**Issue by leeper** [eddelbuettel/drat#31]
I configured a Github access token with the wrong permissions, leading to a failure to fetch my drat repo. The failure resulted in an error that published the access token (see [very bottom of build here](https://travis-ci.org/cloudyr/aws.signature/builds/72574192)). Is it possible to modify the [deploy.sh](https://github.com/eddelbuettel/drat/blob/master/vignettes/CombiningDratAndTravis.Rmd#example-deploysh-script) (from the Travis vignette) so that it can't do that?

**Comment by eddelbuettel** [comment]
@csgillespie : Thoughts on this?

**Comment by csgillespie** [comment]
This sounds bad. I'm away until next  Monday and I'll look at it then.

**Comment by eddelbuettel** [comment]
@csgillespie Any chance you can look at this sooner rather than later?   I have the rest of drat ready for a release.  So the question is: should I wait for you for a possible fix or change, or should we just keep these two issues separate?

**Comment by leeper** [comment]
I think the easiest thing is probably just to redirect stderr to a file, like:

```
git fetch upstream 2>err.txt
```

I have no idea if this will create other problems, but it will solve this one.

**Comment by csgillespie** [comment]
@eddelbuettel  Just about to respond before your ping.

I have been thinking about the problem and the solution that @leeper suggests is the one I came up with. We could pipe all errors from `bash deploy.sh` but I think that's overkill. So I would just propose we change the `git fetch` step to 

```
git fetch upstream 2>err.txt
```

I'll test now

**Comment by eddelbuettel** [comment]
Seems straightforward enough.  Thank you both!

**Comment by leeper** [comment]
Perfect.

**Comment by jangorecki** [comment]
It looks like it prints my unencrypted token on success in [this](https://travis-ci.org/jangorecki/data.table/builds/112159566) build in line 3280.

**Comment by csgillespie** [comment]
I'll investigate

**Comment by csgillespie** [comment]
@eddelbuettel Rather than potentially stuffing other issues with a PR, would you change
```
git push
```

to 

```
 git push 2>err.txt
```
in the vignette.

**Comment by eddelbuettel** [comment]
Done, though I erroneously referred to #37 when I meant #31 here.
