### ISSUE TITLE
remove / prune a repo with higher version number?

### ISSUE THREAD

**Issue by cboettig** [eddelbuettel/drat#32]
Hi @eddelbuettel ,

Is there a way to remove a repo with a higher version number (e.g. with `pruneRepo`?)  I've encountered the case where a developer accidentally committed a higher version number on an older set of sources https://github.com/cloudyr/aws.s3/issues/22#issuecomment-125763465 and wonder if I just need to remove the package src and edit PACKAGES etc manually now...

**Comment by eddelbuettel** [comment]
hi @cboettig -- that strikes me as a little more one-off-ish and not quite ready for a command.  `'git rm` and recompute the indices ...

**Comment by cboettig** [comment]
agreed

**Comment by jangorecki** [comment]
It may be worth to put a note about such case in *DratForPackageAuthors*
