### ISSUE TITLE
drat and travis-ci

### ISSUE THREAD

**Issue by jangorecki** [eddelbuettel/drat#35]
Any canonical way of defining `.travis.yml` file to use packages from drat?
As workaround we can use `r_github_packages` and point particular commit in package repo.
Maybe some trick to *addRepo* before running `r_packages` step? similar way as we can add PPA in `before_install` and then install added package listing it in `apt_packages`.
If there is no easy to use drat with travis I would like to fill FR for this.

**Comment by eddelbuettel** [comment]
Drat provides repositories so I would just do what I usually do in `/etc/R/Rprofile.site`:

```{.r}
## Setting repos
local({
    #options(download.file.method="libcurl")   ## support https, was needed for R < 3.2.2
    r <- getOption("repos")
    r["CRAN"] <- "https://cran.rstudio.com"
    r["ghrr"] <- "https://ghrr.github.io/drat"
    options(repos = r)
})
```

So in that sense there is no defiency in the drat package.  If you want something to be done in travis-ci you would need to file an issue there, and/or talk to @craigcitro.

**Comment by eddelbuettel** [comment]
And all this is in fact already discussed [in this r-travis issue ticket #160](https://github.com/craigcitro/r-travis/issues/160) so I am closing this, ok?  

If you have drat specific issues or questions, by all means do bring them here.

**Comment by jangorecki** [comment]
Sure, this is a gap to address by travis team. I'm surprised I cannot find R environment variable like `R_REPOS` which would be useful here.

**Comment by eddelbuettel** [comment]
Craig may well take a patch.  In the past we were more focus on a sole repository ...
