### ISSUE TITLE
drat with binary files

### ISSUE THREAD

**Issue by vnijs** [eddelbuettel/drat#4]
I use `minicran` to create a repo on github (https://github.com/mostly-harmless/radiant_miniCRAN). This provides some control over dependencies when a few hundred students are using your software. Drat seems like an interesting option to enhance the workflow. Does `drat` also work with binary files?

**Comment by eddelbuettel** [comment]
Not yet but it could.

I live on Linux where I have no binary files but only sources. I built similar setups in the past for Windows, and I know it can be done.  I have no use Windows, and do not use OS X anywhere---so I would not be the best person to write a patch.  But `installPackages()` could be extended to do the right thing on `.tgz` which, IIRC, is the extension used on OS X.  Interested to collaborate / prepare a pull request?

Again, my main issue is that I _cannot test this_ so I won't lead this.  But I did already mark it in the [TODO.md](https://github.com/eddelbuettel/drat/blob/master/inst/TODO.md).

**Comment by mostly-harmless** [comment]
Sounds like fun. I am putting it on my todo list but it will probably be a couple of weeks before I can get started on this.


—

**Comment by JanSchulz** [comment]
This would be a great solution for problems like https://github.com/takluyver/IRkernel/issues/54...

**Comment by eddelbuettel** [comment]
Precisely, especially if one can get a package built via win-builder ...  Either way, once you "somehow" managed to create a binary, this makes it possible to have users install those without fuzz.  Now in really hard cases of needing other libraries on the system, environement variables set etc pp to run something they still need to do that.

**Comment by JanSchulz** [comment]
So, what can I do to help this along?

I've some rudimentary experience in installing package from source, but actually I've no idea how to build a binary package which could uploaded somewhere...

**Comment by eddelbuettel** [comment]
Oh, via a few things:
- just having someone who regularly works on Windows help as ...
- we need to add support to insertPackage
- and tests that

In essence,  source packages (ending in tar.gz) always go to src/contrib whereas binary packages go to bin/windows/contrib/3.1/  (always major.minor ie dropping the last 3 of 3.1.3)

It is easy to pattern match the file type on input, and we just need to carefully add code that covers this case without breaking anything in the in current source case.

**Comment by eddelbuettel** [comment]
One more thing I forgot: we can use [win-builder](http://win-builder.r-project.org) to generate Windows binaries.  So even if you don't have a full tool chain you can still get access to such packages.

**Comment by eddelbuettel** [comment]
This now works thanks to Jan in Pull Request #16 so I close this.
