### ISSUE TITLE
insertPackageDeps

### ISSUE THREAD

**Issue by jangorecki** [eddelbuettel/drat#41]
A FR for new function *insert package dependencies* to mirror all non-locally stored packages.
It could take `package` and `repos` arguments and download all the R dependencies recursively - latest tar.gz sources.
The advantage is to create sustained environment for your package, well historized, easy to maintain,  and would work for offline installation.

**Comment by eddelbuettel** [comment]
I think this is what miniCRAN does, and it is said to work perfectly well with drat.

And I believe we have some testimony to this effect.  Can you check the vignette by @csgillespie ?

**Comment by csgillespie** [comment]
I never got around to writing up the miniCRAN stuff - you're thinking of the drat. I'll try and get simple example working and post it here. We can develop it into a vignette.

**Comment by csgillespie** [comment]
Example drat/miniCRAN script
```
## Assume we're in the drat directory
## Switch to gh-pages
repo = git2r::repository(".")
git2r::checkout(repo, "gh-pages")
git2r::pull(repo)

## list packages to get CRAN versions
pkgs = "drat"

## all_pkgs  - vector of dependencies
all_pkgs = pkgDep(pkgs)

## PACKAGES is automatically updated
miniCRAN::makeRepo(all_pkgs, path = ".", type = "source")
#miniCRAN::makeRepo(all_pkgs, path = ".", type = "win.binary")

git2r::add(repo, file.path("src", "contrib", "*.tar.gz"))
git2r::add(repo, file.path("src", "contrib", "PACKAGES"))
git2r::add(repo, file.path("src", "contrib", "PACKAGES.gz"))

git2r::commit(repo, "First version using miniCRAN")

```

**Comment by jangorecki** [comment]
Thanks @csgillespie. I will also put here my script once I would use that without `miniCRAN` dep as both tasks (checking pkg dependencies and downloading source pkgs from cran) seems to be doable with just default packages.

**Comment by eddelbuettel** [comment]
Sounds good.  I don't want to duplicate what miniCRAN already does (and well) but I would be interested in a 'mini-mini-CRAN" scriptlet if you get that going.

@csgillespie Yes, sorry, it was comment re a course you taught, not a vignette.  My bad.  But we should "vignette-ify" this.
