### ISSUE TITLE
github.io URL does not seem to work

### ISSUE THREAD

**Issue by rappster** [eddelbuettel/drat#42]
Hi Dirk,

I'm finally came around giving drat a test drive and so far I like it a lot!

Only problem though: everything works fine locally, but my github.io URL ([http://rappster.github.io/drat](http://rappster.github.io/drat)) does not seem to work as I'm getting a 404 error.

Here's what I did:
1. I followed the instructions in your [vignette](http://eddelbuettel.github.io/drat/DratForPackageAuthors.html) which resulted my drat repo: [https://github.com/rappster/drat](https://github.com/rappster/drat)
2. I build my package and added it to the repo via `drat::insertPackage(...)`
3. I pushed my local git repo state (branch `gh-pages`) to GitHub and also made `gh-pages` the default branch (probably not necessary, but that's the last thing I could come up with for troubleshooting)

Any clue of what might have gone wrong?

**Comment by eddelbuettel** [comment]
Seems to work for me:

```r
R> library(drat)     
R> addRepo("rappster")         
R> AP <- available.packages()        
R> ind <- which(rownames(AP) == "timetrackr")
R> options(width=100)
R> AP[ind, ]
                                     Package                                      Version 
                                "timetrackr"                                        "0.1" 
                                    Priority                                      Depends 
                                          NA                                           NA 
                                     Imports                                    LinkingTo 
                                        "R6"                                           NA 
                                    Suggests                                     Enhances 
      "knitr, rmarkdown, settings, testthat"                                           NA 
                                     License                              License_is_FOSS 
                                "GPL (>= 3)"                                           NA 
                       License_restricts_use                                      OS_type 
                                          NA                                           NA 
                                       Archs                                       MD5sum 
                                          NA           "a091b722950f756343f097fa2e54a1c1" 
                            NeedsCompilation                                         File 
                                        "no"                                           NA 
                                  Repository 
"http://rappster.github.io/drat/src/contrib" 
R> 
```

**Comment by rappster** [comment]
Wow, thanks for the quick reply!

Hmm, it does for me too :-/

Thanks for taking the time / sorry to have bothered you. I thought that [https://rappster.github.io/drat/](https://rappster.github.io/drat/) would display a FTP-like directory structure. Hence the question.

**Comment by eddelbuettel** [comment]
You can browse it on GitHub by switching branches.  And http, last I checked, is not spelled ftp ;-)

**Comment by rappster** [comment]
Can't argue with that ;-) Thanks again
