### ISSUE TITLE
Suggestion: Remove trailing slash on repo dir

### ISSUE THREAD

**Issue by kwstat** [eddelbuettel/drat#45]
On Windows, a path with a trailing slash is NOT a file.

```
file.exists("//local/PRAN/") # false
file.exists("//local/PRAN") # true
```

Currently (drat 0.1.0), the following line errs because of the trailing slash.  Here "//local/PRAN/" is a local network folder.

insertPackage("pkg_1.tar.gz", "//local/PRAN/")

Error: Directory //local/PRAN/ not found

Without the trailing slash, the function call works fine

insertPackage("pkg_1.tar.gz", "//local/PRAN")

This feature request is just a "nicety" for people like me that accidentally add the trailing slash and wonder why insertPackage cannot find the directory.

**Comment by eddelbuettel** [comment]
Can you point to the code?  That surely is a variable; I don't recall every typing the word PRAN.

(Otherwise I don't doubt the issue.  I probably wanted `dir.exists()` anyway.

**Comment by eddelbuettel** [comment]
So can you try

```r
insertPackage("pkg_1.tar.gz", "//local/PRAN")
``` 

instead ?

**Comment by kwstat** [comment]
Sorry I wasn't more clear the first time.  I've added a few additional comments that may help.

**Comment by eddelbuettel** [comment]
In general, no.  This is a small project, and we're not here to hold all possible hands.  

If you supply bad input, you get the result.  What's next?  Search the directory because you misspelled the file name?  Read your mind because you _meant_ to supply a different version?  

Slippery slope; best to avoid.

**Comment by eddelbuettel** [comment]
It would by the way be pretty trivial for you to write a local wrapper which does all sorts of local checks for files, directories, permissions, ... -- all things I cannot really generalize.

**Comment by kwstat** [comment]
I understand.  Thanks for your consideration.  I will note that both dir("c:/x") and dir("c:/x/") work fine, so it appears that dir() does try to read my mind.  :-)

I will follow your suggestion and wrap a function around insertPackage.

**Comment by eddelbuettel** [comment]
But I *will* make the change from `file.exists()` to `dir.exists()`.  That looks like like a typo / think as I used `file.exists()` two lines before to test for the tarball.

So all good after all :)

**Comment by kwstat** [comment]
Thanks.  Appreciate your work on this package.
