### ISSUE TITLE
FR: addRepo and getOption("dratRepo", "~/git/drat")

### ISSUE THREAD

**Issue by ctbrown** [eddelbuettel/drat#49]
I am curious to know why `addRepo` does not also set the `dratRepo` option or at least have it do it optionally.  I don't think most of the users have multiple drat repositories and I suspect they are using the same drat repository as both module user and authors.  At present me `.Rprofile` sets both. Seems a bit odd from the interface perspective.

**Comment by jangorecki** [comment]
Don't know about *most users* but I usually have dedicated drat repository for each developed package. In production environment I include all dependencies of a package to its drat repo to *freeze* dependencies. This way I always have a valid version of all dependencies for each developed package. That would not be possible when using just single repo.

**Comment by ctbrown** [comment]
That's a interesting use of drat. I hadn't thought of that. 

My response to is that drat would still work for you, since I am suggesting having `addRepo` set `options( dratRepo=alturl )` when it is not previously set and possibly only when the Repo is local. Arguments would be the same. So you could use `addRepo`, `insertPackage`, etc. as normal.  

It could also be more clever than that.

**Comment by eddelbuettel** [comment]
Hi Chris. 

I think I liked the separation because our use of `addRepo()` points to a shared drive where the use goes through an internal webserver pointing at the repo.

I don't see a strong case yet for altering the interface.  Maybe you can get by with simple set of local helper functions giving you the wrapping you desire?

**Comment by eddelbuettel** [comment]
Closing this stale issue.
