### ISSUE TITLE
insertPackage could accept "fields" argument passed to write_PACKAGES

### ISSUE THREAD

**Issue by jangorecki** [eddelbuettel/drat#53]
So user can have better control over what metadata are being part on the PACKAGES index file.

**Comment by eddelbuettel** [comment]
The idea of opening a issue ticket is to give me a moderate and reasonable amount of time to actually look at the ticket, read it and comment.

Immediately following up with PR is useless.

Please motivate why all users of drat need a new field.

**Comment by eddelbuettel** [comment]
A priori I am not in favour of doing anything which R itself does not do.  One _key_ argument for drat is that _everything_ is as plain vanilla as possible, and that the exact same tools are used.

**Comment by jangorecki** [comment]
but this is what R do `tools::write_PACKAGES`. Why not use metadata from DESCRIPTION file to build PACKAGES index? I would say this is a feature of base R / tools vs drat at the moment.

**Comment by eddelbuettel** [comment]
oh, I see -- you got a point there.  makes it way more elegant and I am starting to warm up to it.

patch then lets you clobber _your_ PACKAGE with whatever you want to put, everybody else gets what they always had and we have a path forward.

I think we can do that.  lemme give it a day.

**Comment by jangorecki** [comment]
should be doable with `...` instead of new argument

**Comment by eddelbuettel** [comment]
or new argument with default that is set, provided we don't mess with the order

**Comment by jangorecki** [comment]
Fields expected by default won't be reordered, new lines from provided `fields` are after the defaults. What do you think about `...` in 66e407a?

**Comment by eddelbuettel** [comment]
looks good. Is `...=...` legit?  Don't think I have seen that...

**Comment by jangorecki** [comment]
Sure it is.

**Comment by jangorecki** [comment]
While `...=...` is legit, it shouldn't be here, as `write_PACKAGES` doesn't have `...` arg. Updated in latest commit.

**Comment by eddelbuettel** [comment]
Well caught, thank you.
