### ISSUE TITLE
insertPackage could return relative path of inserted file

### ISSUE THREAD

**Issue by jangorecki** [eddelbuettel/drat#58]
Currently it returns NULL. It would be nice to have relative path returned of the package that was inserted. For source package it is easy (`src/contrib/...tar.gz`) , but for binaries packages one would need need to use `getPathForPackage` (internal function). So returning relative path to `repodir` would helps in further actions that depends on inserted package.

**Comment by eddelbuettel** [comment]
But access can be file based, or via http.   So how about not doing this but letting the user run `available.package()` to actually get it via the repository infrastructure?

**Comment by jangorecki** [comment]
`available.packages` won't answer the question *what file was just inserted*.

**Comment by eddelbuettel** [comment]
The user knows that _because he just made the call_.

**Comment by eddelbuettel** [comment]
You can also run `available.packges()` twice and compare the results. That, in essence, is CRANberries.

**Comment by jangorecki** [comment]
User needs to know the platform and R version to be able to produce exact path of inserted file, so in the end it is easier for user to use unexported `drat:::getPathForPackage`. Proposed change would makes it much easier, without sacrificing anything.

**Comment by eddelbuettel** [comment]
Jan, I think it is outside the scope. I am not building a file manager.    This is about repo tools.

We have a function to insert into a repo.  Afterwards, use `install.packages()` and friends to retrieve.

If you happen to know the physical location of your repo, you can do it locally.  Or just concatenate repodir and file, ie wrap `insertPackage()` into your own `myInsertPackage()`.  

I do not think you have convinced me that me need this.  I don;t want to be a meanie but I this needs to be closed.
