### ISSUE TITLE
insertPkg working directory

### ISSUE THREAD

**Issue by schloerke** [eddelbuettel/drat#59]
Similar to setting the working directory back to the `curwd` in https://github.com/eddelbuettel/drat/blob/master/R/insertPackage.R#L82 , could the same be done after maybe commit'ing https://github.com/eddelbuettel/drat/blob/master/R/insertPackage.R#L125 . 

It would really be helpful when supplying relative routes for the `repodir` and trying to prune or archive after commit'ing.

Thank you for the awesome package!
- Barret

**Comment by schloerke** [comment]
Sure!  I'm using `repodir = '.'`.  When I call `drat::insertPackage(file=MYFILE, repodir = '.', action = 'prune')`, it fails. I think both of your examples have fully defined paths (default starts from '~/' and the other starts from '/') where I'm using a relative directory.

https://github.com/schloerke/travisDrat/blob/master/R/drat.R#L146

**Comment by eddelbuettel** [comment]
Would changing one directory above and then called down to that directory (rather than `'.'`) work?

**Comment by schloerke** [comment]
I can't test right now, but I bet if I called it with normalizePath('.') it
would work fine

**Comment by eddelbuettel** [comment]
This can be closed, the lack of following suggests the issue is addressed.  If more is needed please reopen and ideally demonstrate with small reproducible examples why.
