### ISSUE TITLE
Any way to host a repository privately but not on a local network?

### ISSUE THREAD

**Issue by daattali** [eddelbuettel/drat#60]
Suppose I have a packages I want to share with a few remote friends.

I was thinking I could either use a private GitHub repo, or host the packages on a virtual server (such as amazon EC2) and let me friends use that server as the repository. I couldn't see anything in the documentation that implies this is possible though.

Is there/could there be a way to support this?

**Comment by eddelbuettel** [comment]
If I follow, then what you describe seems orthogonal to whether your repo is public or private. -- drat just needs write access somewhere to have R write an updated PACKAGES file. That can be `~/git/someDir` but drat does not what the remote to repo 'someDir', nor does drat need to know.

You can also run drat just find without git -- on the reading side R just uses `installed.packages()` over http, or via a file:/// URL.  

I hope I am making sense here to you, if not may see different drat vignettes and/or refine the question here.

**Comment by eddelbuettel** [comment]
In other words, if hosted remotely, this turns into standard 'how to I protect a website' issue and you'd have to tell R how to run `update.packages()`, `install.packages()`, ... which may well work via `curl` and tokens.

drat just creates the repo.  The transport layer is all you.  Makes sense?

**Comment by daattali** [comment]
Yep makes sense. I haven't actually tried drat yet, just read the vignettes and was wondering if there are existing use cases of people placing their repos behind password protection.

If I host on a private server, inserting the package is easy because I personally have access to the web server so I can run the commands without problem. But for other people to run the `addRepo()` command,  I'm not sure how to use the URL to tell drat to read from a server that needs user/pw authentication. 

I understand this might be outside the scope of drat though. Or maybe it'll be as easy as just specifying the user:pw in the url.

**Comment by eddelbuettel** [comment]
You have to take each command and operation at a time.  `addRepo()` is just a shorthand for setting `options("repos")`.  And we're back to square one: you have a transport problem.  

You can tell R to run _all_ its download operations via an external program like `curl` (the binary).  That way it is back to you to deal with whatever armada of proxies, firewall, bonfires, and whatnots you have between your machine and the sacred remote repo.

**Comment by daattali** [comment]
Right so this isn't a drat issue,  feel free to close this issue,  thanks
for your patience
