### ISSUE TITLE
cannot install CRAN packages once local drat repo is added

### ISSUE THREAD

**Issue by geetlord** [eddelbuettel/drat#62]
I am new to using the drat package, but in general I seem to have it working. I have built a local repository stored on a Windows network drive at our office. I can successfully add the repo using:
 `drat::addRepo("LocalRepo", "file:S:/shared/files/LocalRepo")`
at this point install.packages("LocalPackage", type= "source") works perfectly. However, if I try to add a package from the CRAN repositories:
 `> install.packages("ggplot2")`
I get the following:
`Warning in install.packages :
  cannot open compressed file 'S:/shared/files/LocalRepo/bin/windows/contrib/3.4/PACKAGES', probable reason 'No such file or directory'
Error in install.packages : cannot open the connection`

Is there a way to avoid this problem?

**Comment by eddelbuettel** [comment]
You are doing it wrong.  The drat repo is _in addition_ to other repos (like CRAN or BioConductor).  Do something like this:

```r
    r <- getOption("repos")
    r["CRAN"] <- "https://cran.rstudio.com"
    r["ghrr"] <- "https://ghrr.github.io/drat"
    options(repos = r)
```

which you could have in `~/.Rprofile`.

**Comment by geetlord** [comment]
I understand that. My goal was to contain local analysis code regularly used in our office in an easily accessed repository that would exist outside of and in addition to CRAN etc... The problem was that installing the new repo seems to shut off access to CRAN. 

After more digging I think I found the root issue. Because the packages inserted in the drat repo are source packages, for some reason R forces all of my calls to install.packages() to require the option type = "source" like this:
` > install.packages("ggplot2", type = "source")`
Alternatly it seems like I can create the folder structure:
S:/shared/files/LocalRepo/bin/windows/contrib/3.4/
with an empty PACKAGES file in it. As new versions of R are released I'll need to add additional folders to .../windows/contrib/

**Comment by eddelbuettel** [comment]
Ok.  If you can think of a patch to the existing documentation to make this clearer I will of course consider it.
