### ISSUE TITLE
Drat doesn't know about mac.binary.el-capitan

### ISSUE THREAD

**Issue by alexbull** [eddelbuettel/drat#64]
macOS R now looks in "bin/macosx/el-capitan/contrib", not "mavericks".

```
R> contrib.url(getOption('repos'), type=.Platform$pkgType)
[1] "https://cloud.r-project.org/bin/macosx/el-capitan/contrib/3.4"  
```

It seems this stems from the fact that on R 3.4, `.Platform$pkgType` returns `"mac.binary.el-capitan"`, but `getPathForPackage` doesn't know about this. This is documented [deep in the R documentation about package installation](https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#macOS-packages).

**Comment by eddelbuettel** [comment]
Nice catch.  Do you think you may be able to work on a pull request?   I can't really test it for lack of a macOS box...

**Comment by eddelbuettel** [comment]
This is now taken care of thanks to @nfultz
