### ISSUE TITLE
Can we avoid the warning of cannot open binary package index?

### ISSUE THREAD

**Issue by dracodoc** [eddelbuettel/drat#71]
I finally tried to host my package in drat, it's simpler than what I thought, but with some minor details.

One minor issue is that `install.packages` tries to find binary package first and gives error messages when only source packages are hosted.

```r
> drat::addRepo("ctmm-initiative")
> install.packages("ctmmweb")
Warning in install.packages :
  unable to access index for repository https://ctmm-initiative.github.io/drat/bin/macosx/el-capitan/contrib/3.4:
  cannot open URL 'https://ctmm-initiative.github.io/drat/bin/macosx/el-capitan/contrib/3.4/PACKAGES'
installing the source package ‘ctmmweb’
```

It doesn't block any work, just some warnings may surprise users and make them to thinking something is wrong.

However if I keep the drat repo in options, installing any other package will have this warning too

```r
> install.packages("git2r")
Warning in install.packages :
  unable to access index for repository https://ctmm-initiative.github.io/drat/bin/macosx/el-capitan/contrib/3.4:
  cannot open URL 'https://ctmm-initiative.github.io/drat/bin/macosx/el-capitan/contrib/3.4/PACKAGES'
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/git2r_0.21.0.tgz'
```

This becomes annoying now.

Can we create an empty binary package index to avoid this warning?

**Comment by eddelbuettel** [comment]
That is architecture dependent.  I am sure it would behave differently on Linux (where "source" is default) and probably on Windows (which may fail if you only pushed a macOS binary).

**Comment by dracodoc** [comment]
What I means is that I only host source package (since making binary package is not really needed for my pure R package), but create all the empty folders and some empty package index.

I'm not sure if that's possible though.

**Comment by eddelbuettel** [comment]
That is all on your end, so why don't you try it?  

If it all works to your liking maybe you can document it and we mention it in the FAQ or make a helper function?

**Comment by dracodoc** [comment]
OK, I'll try it when I got time.

**Comment by dracodoc** [comment]
PR created via #73

**Comment by eddelbuettel** [comment]
Here is a suggestion:
- describe what problem you are seeing
- describe how you would want to fix it
- _maybe_ create a prototype locally
- convince me that I want a PR

and only then file a PR.  I hate to close them, but submitting without discussion is not a good plan.

**Comment by dracodoc** [comment]
OK. How about this, I create separate issues for each point I want to make, link to the meaningful diff in my repo. You can have check my repo and decide whether to incorporate them selectively.

**Comment by eddelbuettel** [comment]
Yes, one at a time. Ideally small, concise, documented and understandable.
