### ISSUE TITLE
Improve the documentation

### ISSUE THREAD

**Issue by dracodoc** [eddelbuettel/drat#72]
This will be one of several issues created by me. I think it's easier to discuss each individually. It includes several points, but all about documentation.

### using customized github repo name 

`drat` name is a little bit odd to me, though it's not a real problem as a package name. However users may want to create their github repo with a different name. drat will be alien for anybody heard it in first time.

The documentation all assumed the github repo will be named as drat. It seemed that you can customize the repo name through drat::initRepo, but I didn't find how to work with customized name with other functions according to help and vignettes. 

If I have more time I could try it and find out more details. For now I suggest at least make it obvious in documentation.

### drat package users don't even need to install `drat`

I understand the `drat::addRepo` usage has the advantage that user can upgrade packages later. But that only works if user keep it in options permanently. Since almost every drat package will has its own drat repo, that could means quite some repos saved in user options. And every normal package installation will need to check every repo in list.

I think it's often favorable to just use the repo in session for one time. Then why not just tell package user that they don't even need to install `drat`? Of course `drat` is very small and with little dependencies, still one less dependency may be a positive point for end users.

  I suggest to add some example like this in the vignette for package users:

```r
install.packages("pkgname", repos = c(getOption("repos"),
                                      "full drat repo url"))
```

**Comment by dracodoc** [comment]
OK. I think the possible action could be improve the documentation, at least for the customized repo name. I'll try myself and create a documentation PR to include the actual details.

**Comment by dracodoc** [comment]
I learned about drat a long time ago in a stackoverflow question. At that time I didn't use it because I have some doubts after reading documentation. Recently `devtools::install_github` wasted quite some of my time so I decided to try drat. It turned out be easier than I thought, and it works. 

However I feel there are multiple places in documentation can be improved so that it's easier for new users to adopt it.

I'll try to write some draft and submit for review.

**Comment by eddelbuettel** [comment]
I sometimes joke that we wrote more documentation than code for drat, but there is always more than can be said.  It is sometimes hard to generalise from one's very personal view so that may be missing for you may be there for others.   But always open to making the documentation clearer.

The direct install.packages() use has of course worked from day one; some repos show it for one-off installs.  I personally do not find it clearer -- your example has a second option with sub-function call.  All that can scary newbies too.

**Comment by dracodoc** [comment]
I think that example can be an option because it's clear we are just using another regular repo. `drat::addRepo` definitely looks clean but user may wonder what it does (and it modified the global envrionment).

And I feel the "no other package needed for users" actually is a strong point compare to `devtools`, otherwise it may look like just another tool like `devtools::install_github` for uninformed users.

**Comment by eddelbuettel** [comment]
I understand your point, there is no reason to reiterate.  It is simply a different use case: all you care about here it a one-shot one-off install; I also often think about a repo added more repeatedly,  Both uses coexist.
