### ISSUE TITLE
Improve various help documents

### ISSUE THREAD

**Issue by dracodoc** [eddelbuettel/drat#74]
I'll put all my edit on help documents here. They are relatively minor, no need to create separate issue for each topic.

1. `addRepo`
See changes [here](https://github.com/dracodoc/drat/commit/229b95f8d3e3d19f88eef43235a5db157c7f6e2d#diff-81eab1ece9ab048ab5a5daddf72bd59e). Only the R file diff is needed since Rd is generated.

    I removed one extra `(`, added notes of `getOption("repos")`, modified the first code example which can be confusing, because user will not expect "drat" to be a github user name.

**Comment by eddelbuettel** [comment]
I am ok on the removal of the stray `(`, I don;t understand the focus on `getOption("repos")`.  That has little to do with drat and `install.packages()` etc use it.

**Comment by eddelbuettel** [comment]
So here is a simpler change:

```diff
modified   R/addRepo.R
@@ -5,10 +5,11 @@
 ##' repositories.  This function aids in the process, and defaults to
 ##' adding a \sQuote{drat} archive at GitHub under the given account.
 ##'
-##' This function retrieves the current set of repositories and adds
+##' This function retrieves the current set of repositories (see
+##' \code{getOption("repos") for the current values) and adds
 ##' (or overwrites) the entry for the given \sQuote{account}. For
 ##' non-GitHub repositories an alternative URL can be specified as
-##' \sQuote{alturl} (and assigned to \sQuote{account}.
+##' \sQuote{alturl} (and assigned to \sQuote{account} as well).
 ##'
 ##'
 ##' An aliased function \code{add} is also available, but not exported
```

**Comment by dracodoc** [comment]
Yes `getOption("repos")` probably is too obvious for advanced users, just I didn't realize it (or not sure the exact name of the option) when I first used `addReo`.

Also the example `addRepo("drat") ` probably should be changed.

**Comment by dracodoc** [comment]
@eddelbuettel 
I think the example `addRepo("drat")` is still confusing, because user will not expect that to be github user name.

And I was planning to use this issue for various help improvements so I don't need to create multiple issues just for very minor edits. It's closed now so I have to open new issues, or just forget about it.
