### ISSUE TITLE
Support customized branch name in initRepo

### ISSUE THREAD

**Issue by dracodoc** [eddelbuettel/drat#75]
`insertPackage.R` supported customized branch name through `getOption("dratBranch", "gh-pages")`. However `initRepo` doesn't support this yet. 

For `insertPackage`, I made a minimal change to add `branch` as a parameter [here](https://github.com/dracodoc/drat/commit/309f62cfb79d85d5617a4cb7289de8ee0afcd7d6#diff-dad8000271e2fdb632eaebb19fb6d039). 

There is default value, and it's still taken from option, so previous usage will not be interfered. But a parameter make it easier for user to make one time change - most users will use `gh-pages` as default option, but maybe change one time for certain repo. The option approach will make this usage awkward.

**Comment by eddelbuettel** [comment]
Why do we need it?  Shell pseudo code

- `git init`                                              
- `git checkout -b somebranch`    

This creates an empty (branchless) repo and then adds a branch.  `drat` supports the same.

**Comment by dracodoc** [comment]
I'm not sure I understand the comment. `branch` is to support customized branch names, since `gh-pages` is hard coded in several places. `initRepo` don't have an option to use customized branch names, using shell doesn't help with that.

I was talking `insertPackage` first because that change is minimal and easy to see the difference. I want to make the change because using option to customize branch is kind of rely on global variable and may not work in different environment.

My change should be compatible with the option usage, so there is nothing needed to change if user want to use `option`.

**Comment by dracodoc** [comment]
For `initRepo` my commit was added on top of other changes so it is not obvious. I'll try to make a separate branch to focus on this first.
