### ISSUE TITLE
archivePackage not creating package index

### ISSUE THREAD

**Issue by jrowen** [eddelbuettel/drat#77]
I'm trying to use `devtools::install_version` in conjunction with packages that have been saved to an internal repo using `insertPackage` with `action = "archive"`.  This process fails due to [`remotes::package_find_repo` ](https://github.com/r-lib/remotes/blob/master/R/install-version.R#L54-L76) being unable to find the archive index file at `/src/contrib/Meta/archive.rds`.  It appears that `insertPackage` does not create/update an index file at this location.

Could functionality for writing an archive package index be included in `archivePackages` or is this best done outside of this package?

**Comment by eddelbuettel** [comment]
What you describe is not how I work but maybe you describe a minimal changeset first?  If we agree maybe you can prepare a subsequent pull request?

My workflow is different.  I prepare tarballs and insert them.  That updates indices.  Archival is done less often; it is possible that indices are not updated there.  That should be "cheap" to fix.

Am I understanding your issue correctly?

**Comment by jrowen** [comment]
I'm trying to somewhat mimic the pip functionality without having to roll my own libraries.  I use drat to push to an internal repo on successful build, and then I'd like to use install_version to control R library versions in containers.

It seems a compatible archive index could be created by creating and index file in the Archive folder and then copying that file to the Meta folder.

I'm open to other ideas if there's a better way.

**Comment by eddelbuettel** [comment]
Well `drat` uses the CRAN tools so _per se_ there is only the newest version listed.  That's just the way it is.

Am I reading you correctly as desiring an index over all available versions?  Could do, but now how CRAN works.   Do you offer yourself read-access to your repo?

**Comment by eddelbuettel** [comment]
Based on your hint, I see that R itself has 

```r
CRAN_archive_db <-
function()
    read_CRAN_object(CRAN_baseurl_for_src_area(),
                     "src/contrib/Meta/archive.rds")
```

but I see no helper function writing this :-/ 

What does come up is a StackOverflow post with a helper function:  https://stackoverflow.com/questions/35584396/how-to-generate-meta-archive-rds-to-be-compatible-with-devtoolsinstall-version

Based on that, do you want to take a stab at creating a function to write this file?

**Comment by jrowen** [comment]
I was hoping there was a shortcut here but maybe not.  Thanks for the
suggestions.  If we can figure this out, I think it can provide a
lightweight approach for library version management.  I'll dig into this
over the next few days and report back.

**Comment by jangorecki** [comment]
If you are simultaneously using different versions of your package then it make sense to produce separate drat repos for each version. Newer version of your dependencies might works fine with your recent version but might eventually fail on older version of your package. Having separate drat repos you have guarantee that your package will work over time because you can include your dependencies there at the time when package version was released. This is what we do when we publish devel version of data.table, all deps (suggested, as we don't have others) are published together with data.table in same drat repo.

**Comment by eddelbuettel** [comment]
@jrowen As I said, my workflow was always "CRAN-alike" so current version it is.  That said, if you can write a simple function to index the `archive/` directory then we may as well add it.  Won't change my usage but hey if it helps someone.

@jangorecki Good point.  There _is_ a reason we "do as CRAN does" because ... it works.  A simple linear index will get you a package, it won't do all the magic rest!

**Comment by jrowen** [comment]
I think something like the code will work for creating an `archive.rds` file.  From my perspective, it would be ideal if this would run with every `insertPackage` call (`action = 'archive'`), but maybe some would prefer these steps to be optional.

```
repodir = '~/git/repo/src/contrib'

archdir = paste0(repodir, '/Archive')
archindex = sapply(
  list.dirs(archdir, full.names = FALSE, recursive = FALSE), 
  function(x) {
    tmp = file.info(dir(paste0(archdir, '/', x)))
    row.names(tmp) = paste0(x, '/', row.names(tmp))
    tmp
}, simplify = FALSE, USE.NAMES = TRUE)

metadir = archdir = paste0(repodir, '/Meta')
dir.create(metadir, showWarnings = FALSE)
saveRDS(archindex, paste0(metadir, '/archive.rds'))
```
And the code below now works as expected.
```
devtools::install_version(
  'rhandsontable', '0.3.6', 
  repos = 'https://raw.githubusercontent.com/jrowen/repo/master')

install.packages(
  'rhandsontable',
  repos = 'https://raw.githubusercontent.com/jrowen/repo/master')
```

**Comment by eddelbuettel** [comment]
Thinking about this some more I am feeling that it is out of scope for `drat`.  This solely for your use via a `devtools` function I do not use ... and the whole reason `drat` was create was to provide a means for _proper repositories_ in the CRAN sense.  As opposed to "random" snapshots of git repo as popularized by `devtools`. 

So this may be best provided at your end. Create a wrapper than inserts into `drat`, archives and updates the archive index.  But it is not really aligned with what `drat` was made for.

**Comment by jrowen** [comment]
Fair enough, I can implement this on my end.

I would note that creating an `archive.rds` file follows CRAN process.  The use case I described may be a bit out-of-scope for `drat`, but other use cases mar arise that are better aligned.

Thanks for the ideas and suggestions.

**Comment by eddelbuettel** [comment]
Yes, not disputing that the file is present there.  And it is easy to create. I am just not sure it is supported by `install.packages()` et al -- the `devtools` extensions are just not as releavant to me.  

Kurt Hornik recently reminded folks that there is an explicit version pinning feature via the website by explicitly mentioning a package and version in the URL. In an email to r-devel on Oct 24 he used this example

    https://cran.r-project.org/package=httr&version=1.3.1
    https://cran.r-project.org/package=httr&version=1.3.0

But I don't think there is a base R command that is equivalent for direct installation.  So I think this is a little out of scope for drat.

**Comment by eddelbuettel** [comment]
Closing as out of scope
