### ISSUE TITLE
Control overwriting

### ISSUE THREAD

**Issue by krlmlr** [eddelbuettel/drat#80]
Currently, `insertPackages()` silently overwrites an existing `tar.gz` of the same version. This default seems dangerous. Would you support an `overwrite` argument to `insertPackages()`, defaulting to `FALSE`?

**Comment by eddelbuettel** [comment]
Good plan!  Check with `file.exists` and if `overwrite` is given proceed else ... warn but proceed?  Or abort with message?

PR would be nice.  Add a ChangeLog entry please too.

**Comment by eddelbuettel** [comment]
This can be closed, the lack of following suggests the issue is addressed.  If more is needed please reopen and ideally demonstrate with small reproducible examples why.
