### ISSUE TITLE
Windows 10: unable to access index for repository

### ISSUE THREAD

**Issue by jarioksa** [eddelbuettel/drat#81]
I have tried to set up a repository to make life easier for others, but they seem to run in trouble (I have had no problems, but everything works smoothly for me). On the first day, I have had two messages of failures, both from Windows 10 users, and both with this error message:

```
(converted from warning) unable to access index for repository jarioksa.github.io/drat/src/contrib:
scheme not supported in URL 'jarioksa.github.io/drat/src/contrib/PACKAGES'
```
Is there anything I can do (apart from closing the repository)?

Background & Details:

The package in the repository is not downloaded directly, but it is a non-CRAN package that is needed by another package in github (let's call it the Main Package). In that package I had in DESCRIPTION:
```
Additional_repositories: jarioksa.github.io/drat
```
The Main Package is in github (and will remain there unless we can fix this issue), and the users have applied `devtools::install_github()` to install the Main Package, and the idea was that this non-CRAN package would be looked at the drat directory if needed. In my system this worked OK both in the `R CMD check --as-cran` and also worked when I tried installation. However, it failed with users. A funny thing here is that neither of these users actually needed this drat package because they had followed our more involved instructions and already installed the package. The installation still wanted to peek at the `Additional_repository`, but it could not do so – at least not in Windows 10 (_n_ = 2).

After the first report, I used Win-Builder to produce a Windows binary of the package and also inserted that into the repository, but the second report came several hours later so that this probably did not help.

Is there something we can do, or is it best to forget drat?

**Comment by jangorecki** [comment]
How did you documented to install the package from your drat?
Did it make difference if user uses `https` or `http`?
I recall that `install.packages(method="curl")` sometimes helped on such error.
I used drat, `tools::write_PACKAGES`, and `Additional_repository` field and never had problem that I couldn't fix, so forgetting drat (or `tools::write_PACKAGES` essentially) shouldn't be necessary.

**Comment by jarioksa** [comment]
I did not document that install by any means, except

- People install another package with `devtools::install_github`
- and that another package has `Additional_repositories` directive in `DESCRIPTION` pointing to drat.

The failure comes from that `Additional_repositories` because it emerged even when people did not need to use that drat repository.

I had hoped that this was invisible magic for users. It was, but visible & black magic.

**Comment by jarioksa** [comment]
Closing this is OK. It answers this one question: can drat be used to build a repository that can be given as `Additional_repositories` in package `DESCRIPTION`. The answer is "NO".

**Comment by jangorecki** [comment]
@jarioksa the answer is yes, try
```
Additional_repositories: https://jarioksa.github.io/drat
```

**Comment by jangorecki** [comment]
Another working example: https://github.com/jangorecki/big.data.table/blob/master/DESCRIPTION
Lookup `.gitlab-ci.yml` for usage when installing. Although I haven't used with `devtools::install_github` but `utils::install.packages`.

**Comment by jangorecki** [comment]
Note that `Additional_repositories` is currently used only for package check (see WRE). If you want to use that information for automatic dependency resolution you have to code that. I submit proposal to base R to provide such information to user https://github.com/wch/r-source/compare/tools4pkgs#diff-c610281df0839138574292846834cbc5R447-R461
but it wasn't merged.

**Comment by jarioksa** [comment]
Thanks for these. I try to follow these guidelines. I cannot test them myself because everything worked for me all the time: it were the users that ran into trouble and reported their failures. I'll wait for their reports of success (I hope).

**Comment by jarioksa** [comment]
@eddelbuettel I was not shouting "BUG!", and my intention was not suggest there was something wrong in **drat**. I assumed all the time that either I was missing something or that there are some strange interactions or assumptions buried in **devtools** or Windows 10, but I wished somebody would know and lead me to the light. Thanks.
