### ISSUE TITLE
Support for a repo providing also archived packages?

### ISSUE THREAD

**Issue by stefanoborini** [eddelbuettel/drat#84]
It is unclear if drat supports a repo that provides download access to old packages. Say I deploy ggplot 3.0.0, then decide to deploy 3.2.1 using the archive option to insertPackage(). Is the repo still able to provide 3.0.0 if requested e.g with devtools::install_version()? 

It seems to me that to provide this functionality, a Meta directory must also be present, not only Archive. Is there functionality to create this directory and its content?

**Comment by eddelbuettel** [comment]
`drat` supports what `install.packages()` and `update.packages()` can use.

What you describe is not present in those, so no.  You'd have to change Base R first.  Which has no notion of versions (besides "highest wins") such pinning, roll down, ... etc pp.   So, no, we do not have that functionality, and I do not see it arriving any time soon.  I think people would probably gravitate towards Docker, or virtual environments, or ...

**Comment by csgillespie** [comment]
The other obvious solution is to create regular snapshots, e.g. Jan-2019, Feb-2019, ... This is also what RStudio pkg manager and MRAN provide.

This solution doesn't quite do what you are after, but I'm not sure you would want to install ggplot2 v3.0.0 __now__ with all the ggplot2 dependencies from the most recent versions.

**Comment by stefanoborini** [comment]
@eddelbuettel devtools has a functionality to install a specific version of a package with devtools::install_version() What it does is to check the Archive directory and the Meta directory, downloads the specified version, and installs it.

**Comment by stefanoborini** [comment]
@csgillespie when we provide software, we need to certify the software against a specific version of its dependencies. We can't rely on pinning against a snapshot, because some versions may be in the past, while other softwares have moved on.

**Comment by csgillespie** [comment]
@stefanoborini But the snapshot would include __all__ of the R dependencies, i.e. drat would clone CRAN. To reproduce the other dependencies, e.g. R versions, then you could use docker.

**Comment by eddelbuettel** [comment]
@stefanoborini I said it once, I'll say it again.  We work with Base R.

You can do whatever you want with `remotes` (you are behind, actually, as that code has not been in `devtools` for years but is merely re-exported).  Next time you run `update.packages()` it would still pivot to the current version.   But you are free to create yourself an `Archive/` section.  When I need those, I do it by hand.  

(And for what it is worth, I even sometimes / routinely "cache" older versions for some scripts by tweaking `.libPaths()`.  But that is a hack.)

So as I said before, R does not support what you desire, so I see no point adding it here.

**Comment by stefanoborini** [comment]
@csgillespie I can't use docker. We are not allowed to use docker here.

**Comment by stefanoborini** [comment]
@eddelbuettel python has no problem with my scenario

**Comment by eddelbuettel** [comment]
You are free to build your own solution, possibly on top of `drat`.  But as we tried to explain, we do not see this as valuable for `drat`.  And I am now locking this discussion because we are past the point where this was useful.
