### ISSUE TITLE
missing setwd(curwd) in insertPackage

### ISSUE THREAD

**Issue by wahani** [eddelbuettel/drat#9]
The function `insertPackage` seems to have the side effect to change the working directory. Actually it is set at several places, but in the case of `commit = TRUE` it is not reset to `curwd`. Maybe a 
```r
on.exit(
  setwd(curwd)
)
```
takes care of it and avoids repetition for all if-clauses. Furthermore it would restore the working directory even if errors occur...

**Comment by eddelbuettel** [comment]
Yes, thanks, could do.

**Comment by eddelbuettel** [comment]
That is [taken care of now](https://github.com/eddelbuettel/drat/commit/1c4704ac1810b92b75669997a8f9d4656d237d6f), thanks again for the suggestion.
