### ISSUE TITLE
HTML error - attempting to install drat from GitLab

### ISSUE THREAD

**Issue by iembry** [eddelbuettel/drat#91]
Hi, I am using an Ubuntu-based distribution.

I created a directory named drat on my local machine. Within that directory, I created the /src/contrib subdirectory structure. After I built the package `USA.state.boundaries.data`, I used `drat::insertPackage("USA.state.boundaries.data_1.0.0.tar.gz", "/drat/")` to add the package to the existing repository. I uploaded the folder structure to GitLab using the command line. This is my attempt to install the package (along with the warning message):

```
install.packages("USA.state.boundaries.data")
Installing package into ‘/library’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository https://gitlab.com/iembry/drat/src/contrib:
  Line starting '<!DOCTYPE html> ...' is malformed!
Warning message:
package ‘USA.state.boundaries.data’ is not available (for R version 4.0.0)
```

How do I correct the error?

Thank you.

**Comment by jangorecki** [comment]
Hi,
Please include `repos` argument to `install.packages` for easier reproducibility.
It looks like `https://gitlab.com/iembry/drat[/src/contrib]` is an invalid repos url. Under that url there must be a PACKAGES file available.
What you need is `https://iembry.gitlab.io/drat[/src/contrib]`, so you need to publish to gitlab pages. You can find working example of that in https://github.com/jangorecki/r.gitlab.ci/blob/master/.gitlab-ci.yml
note it is a little bit more complex than you need because it also publish windows binaries.

**Comment by eddelbuettel** [comment]
@iembry:  As @jangorecki notes this is not yet fully reproducible.  

Also, `drat::insertPackage("USA.state.boundaries.data_1.0.0.tar.gz", "/drat/")` looks suspicious as the second argument here starts with an _absolute path_ pointing to the top-level directory `/`. 

From what I understand, GitLab should work if its pages support behavior just like GitHub does.  
But to clarify, when writing and creating a repo, `drat` really only sees a local writable directory it copies to, and creates indices in: the PACKAGES file(s).  By pushing to the hosting site this then becomes a downloadable URL we can access, but the pushing and hosting is really a service of the provider we use and not something drat adds actively.

**Comment by iembry** [comment]
Hi @eddelbuettel and @jangorecki, I was able to correct the issues. I had to create a public folder in the drat repository and then move the src/contrib to that public folder. In addition, I created an index.html file and added a css folder to store the CSS file. Now, I have https://iembry.gitlab.io/drat/ available for installing my R packages stored as `drat` repositories. Thank you both for the assistance.

**Comment by eddelbuettel** [comment]
Very good to hear that.  Do you think it would help to just write out the five or six relevant bullet points and make another small vignette, or else a new section / appendix to one?

It sounds very similar to what github does / offers so we should and could also mention it.

**Comment by jangorecki** [comment]
@iembry you can make install commands simpler, not everyone will have `drat` installed.
```r
install.packages("USA.state.boundaries.data", repos="https://iembry.gitlab.io/drat")
```
