### ISSUE TITLE
consolidating files and TOC in a repo managed using `drat`

### ISSUE THREAD

**Issue by FelixErnst** [eddelbuettel/drat#96]
Hi, 

In my mind `drat` currently works like this:
- `insertPackage` adds a package to the correct folder and updates the TOC files accordingly keeping only the latest version. (See example)
- Since `insertPackage` only keeps the latest version, files on disc and information in the TOC files diverge over "time"
- Therefore `archivePackages` and `pruneRepo` are implemented and available via the `action` argument, but they are optional so the files and TOC diverge unless the user is aware of this.
- If a file is deleted and this is the current file, the state of the `drat` managed repo cannot be recovered by `drat`

So my conclusion is, that there needs to be a way to fix this divide. I would like to suggest the following changes:
- `insertPackage` uses `latestOnly = FALSE` as a default
-  to fix a repo, where a file mentioned in the TOC is missing, add the `updateRepo` function
- `archivePackages` and `pruneRepo` should than call the `updateRepo` function to make sure that files and TOC are in the same state.

Suggestions and opinions are very much appreciated.

Felix

PS: that issue lead to PR #95 being thrown over the fence. I like to apologize to the persons standing on the other side 😃

**Comment by eddelbuettel** [comment]
(Let's just call the PACKAGES file 'PACKAGES' for simplicity unless you have deep reasons to prefer TOC.)

Decouping the generation of PACKAGES from the `insert()` step is something we can do.  Maybe even by adding a `nofile` option to `insert()` ....

**Comment by FelixErnst** [comment]
> (Let's just call the PACKAGES file 'PACKAGES' for simplicity unless you have deep reasons to prefer TOC.)

They come always as threes and I didn't like to call them "PACKAGES files" or such thing. So I took a step back and described the meaning/function, which is a table of contents.

> Decouping the generation of PACKAGES from the `insert()` step is something we can do. Maybe even by adding a `nofile` option to `insert()` ....

From my point of view this is not possible, since `write_PACKAGES` always accesses, modifies or creates the PACKAGES files.

What do you mean with a `nofile` argument? `nofile` as in writing no file to disc and just updating the PACKAGES files?

**Comment by eddelbuettel** [comment]
Three? Or one file PACKAGES plus two variants (compressed, rds)?  Anyway...  

> What do you mean with a nofile argument? nofile as in writing no file to disc and just updating the PACKAGES files?

Exactly. "Simpler" than adding a new function and help and ...  But it was just an off the cuff suggestion.  I think you already wrote the updater, maybe we just need to expose it...

**Comment by FelixErnst** [comment]
I made the according changes and re-opened the PR.

**Comment by FelixErnst** [comment]
closed #95
