### ISSUE TITLE
How to show available *.tar.gz files in either README.md or index.html automatically.

### ISSUE THREAD

**Issue by bryanhanson** [eddelbuettel/drat#98]
Alright, admittedly not strictly a `drat` question _per se_ but... is there a way for a `drat` repo to automatically list the `*.tar.gz` files it is holding, and display that file list (as text, not links) in either the `README.md` on a branch or in the `index.html` on the `gh-pages` branch?

I'm  not able to find any magic that github would use on a `README.md` to do such a thing (GFM isn't intended to), but maybe there's a JavaScript incantation that would work on `index.html`?  Asking here 'cause you tend to know such things.

Here's the [repo](https://github.com/r-hyperspec/hySpc.pkgs/tree/gh-pages) I'm testing.

If not, we'll make that list manually each time we update I guess.

**Comment by eddelbuettel** [comment]
This can be closed, the lack of following suggests the issue is addressed.  If more is needed please reopen and ideally demonstrate with small reproducible examples why.

The task at hand here may be addressable via, say, GitHub Actions and post-commit + build scripting but it is a wee bit outside the scope of `drat`.

**Comment by bryanhanson** [comment]
Yes, we figured it out as you proposed via GHA, sorry to leave this hanging out there!

**Comment by eddelbuettel** [comment]
No worries, overdue "spring cleaning".  GHA also just came up in #114 -- if you have recipe, ideally shorter/simpler I'd be all ears!

**Comment by bryanhanson** [comment]
I will read #114 and then compare to what we have. It was built during GSOC last summer and I've been meaning to blog on it.  I need to review our approach too, as my collaborators have tweaked it a bit in the meantime.  Give me a week or so.

**Comment by bryanhanson** [comment]
For the record, in case others wander here, we achieved what we wanted as described in this [blog post](https://chemospec.org/2021/04/11/p19/).
